// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ArcaFace

#ifndef _ARCAFACE_UI_H
#define _ARCAFACE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen2.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_wifi_disabled_png);    // assets/wifi_disabled.png
LV_IMG_DECLARE(ui_img_battery_disabled_png);    // assets/battery_disabled.png
LV_IMG_DECLARE(ui_img_lantern_disabled_png);    // assets/lantern_disabled.png
LV_IMG_DECLARE(ui_img_wifi_0_20_png);    // assets/wifi_0_20.png
LV_IMG_DECLARE(ui_img_battery_empty_png);    // assets/battery_empty.png
LV_IMG_DECLARE(ui_img_lantern_off_png);    // assets/lantern_off.png
LV_IMG_DECLARE(ui_img_wifi_20_40_png);    // assets/wifi_20_40.png
LV_IMG_DECLARE(ui_img_battery_0_25_png);    // assets/battery_0_25.png
LV_IMG_DECLARE(ui_img_lantern_on_png);    // assets/lantern_on.png
LV_IMG_DECLARE(ui_img_wifi_40_60_png);    // assets/wifi_40_60.png
LV_IMG_DECLARE(ui_img_battery_25_50_png);    // assets/battery_25_50.png
LV_IMG_DECLARE(ui_img_wifi_60_80_png);    // assets/wifi_60_80.png
LV_IMG_DECLARE(ui_img_battery_50_75_png);    // assets/battery_50_75.png
LV_IMG_DECLARE(ui_img_wifi_80_100_png);    // assets/wifi_80_100.png
LV_IMG_DECLARE(ui_img_battery_75_100_png);    // assets/battery_75_100.png
LV_IMG_DECLARE(ui_img_gem_transparent_png);    // assets/gem_transparent.png
LV_IMG_DECLARE(ui_img_gem_off_png);    // assets/gem_off.png
LV_IMG_DECLARE(ui_img_gem_disabled_png);    // assets/gem_disabled.png
LV_IMG_DECLARE(ui_img_golem_base_png);    // assets/golem_base.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
