// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ArcaFace

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void setEasterEgg(lv_event_t * e);
void setColorLux1(lv_event_t * e);
void setBrightnessLux1(lv_event_t * e);
void setColorLux2(lv_event_t * e);
void setBrightnessLux2(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
