// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ArcaFace

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void setToBlack2(lv_event_t * e);
void setColorFromScreen2(lv_event_t * e);
void setToBlack3(lv_event_t * e);
void setColorFromScreen3(lv_event_t * e);
void setToBlack4(lv_event_t * e);
void setColorFromScreen4(lv_event_t * e);
void setEasterEgg(lv_event_t * e);
void activateGolemInSequence(lv_event_t * e);
void activateGolemOutSequence(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
