#include "ui/images/ui_img_wifi_0_20_png.c"
#include "ui/images/ui_img_wifi_20_40_png.c"
#include "ui/images/ui_img_wifi_40_60_png.c"
#include "ui/images/ui_img_wifi_60_80_png.c"
#include "ui/images/ui_img_wifi_80_100_png.c"
#include "ui/images/ui_img_battery_empty_png.c"
#include "ui/images/ui_img_battery_0_25_png.c"
#include "ui/images/ui_img_battery_25_50_png.c"
#include "ui/images/ui_img_battery_50_75_png.c"
#include "ui/images/ui_img_battery_75_100_png.c"
#include "ui/images/ui_img_lantern_on_png.c"
#include "ui/images/ui_img_lantern_off_png.c"
#include "ui/images/ui_img_wifi_disabled_png.c"
#include "ui/images/ui_img_battery_disabled_png.c"
#include "ui/images/ui_img_lantern_disabled_png.c"

#include "ui/images/ui_img_gem_red_png.c"
#include "ui/images/ui_img_gem_green_png.c"
#include "ui/images/ui_img_gem_blue_png.c"
#include "ui/images/ui_img_gem_cyan_png.c"
#include "ui/images/ui_img_gem_magenta_png.c"
#include "ui/images/ui_img_gem_yellow_png.c"
#include "ui/images/ui_img_gem_white_png.c"
#include "ui/images/ui_img_gem_off_png.c"
#include "ui/images/ui_img_gem_disabled_png.c"
#include "ui/images/ui_img_gem_transparent_png.c"

#include "ui/images/ui_img_golem_base_png.c"
#include "ui/images/ui_img_golem_off_png.c"
#include "ui/images/ui_img_golem_on_png.c"

