// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
void setColorFromScreen2(lv_event_t * e)
{
	// Your code here
}

void setColorFromScreen3(lv_event_t * e)
{
	// Your code here
}

void setColorFromScreen4(lv_event_t * e)
{
	// Your code here
}

void setToBlack2(lv_event_t * e)
{
	// Your code here
}

void setToBlack3(lv_event_t * e)
{
	// Your code here
}

void setToBlack4(lv_event_t * e)
{
	// Your code here
}

void activateGolemInSequence(lv_event_t * e)
{
	// Your code here
}
void activateGolemOutSequence(lv_event_t * e)
{
	// Your code here
}
