// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ArcaFace

#include "../ui.h"

lv_obj_t * uic_EasterEggResult;
lv_obj_t * uic_EasterButton;
lv_obj_t * uic_Lantern15Icon;
lv_obj_t * uic_Battery15Icon;
lv_obj_t * uic_Network15Icon;
lv_obj_t * uic_Lantern15Label;
lv_obj_t * uic_Lantern15Button;
lv_obj_t * uic_Lantern14Icon;
lv_obj_t * uic_Battery14Icon;
lv_obj_t * uic_Network14Icon;
lv_obj_t * uic_Lantern14Label;
lv_obj_t * uic_Lantern14Button;
lv_obj_t * uic_Lantern13Icon;
lv_obj_t * uic_Battery13Icon;
lv_obj_t * uic_Network13Icon;
lv_obj_t * uic_Lantern13Label;
lv_obj_t * uic_Lantern13Button;
lv_obj_t * uic_Lantern12Icon;
lv_obj_t * uic_Battery12Icon;
lv_obj_t * uic_Network12Icon;
lv_obj_t * uic_Lantern12Label;
lv_obj_t * uic_Lantern12Button;
lv_obj_t * uic_Lantern11Icon;
lv_obj_t * uic_Battery11Icon;
lv_obj_t * uic_Network11Icon;
lv_obj_t * uic_Lantern11Label;
lv_obj_t * uic_Lantern11Button;
lv_obj_t * uic_Container2;
lv_obj_t * uic_Screen2;
lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Lantern11Button = NULL;
lv_obj_t * ui_Lantern11Label = NULL;
lv_obj_t * ui_Network11Icon = NULL;
lv_obj_t * ui_Battery11Icon = NULL;
lv_obj_t * ui_Lantern11Icon = NULL;
lv_obj_t * ui_Lantern12Button = NULL;
lv_obj_t * ui_Lantern12Label = NULL;
lv_obj_t * ui_Network12Icon = NULL;
lv_obj_t * ui_Battery12Icon = NULL;
lv_obj_t * ui_Lantern12Icon = NULL;
lv_obj_t * ui_Lantern13Button = NULL;
lv_obj_t * ui_Lantern13Label = NULL;
lv_obj_t * ui_Network13Icon = NULL;
lv_obj_t * ui_Battery13Icon = NULL;
lv_obj_t * ui_Lantern13Icon = NULL;
lv_obj_t * ui_Lantern14Button = NULL;
lv_obj_t * ui_Lantern14Label = NULL;
lv_obj_t * ui_Network14Icon = NULL;
lv_obj_t * ui_Battery14Icon = NULL;
lv_obj_t * ui_Lantern14Icon = NULL;
lv_obj_t * ui_Lantern15Button = NULL;
lv_obj_t * ui_Lantern15Label = NULL;
lv_obj_t * ui_Network15Icon = NULL;
lv_obj_t * ui_Battery15Icon = NULL;
lv_obj_t * ui_Lantern15Icon = NULL;
lv_obj_t * ui_EasterButton = NULL;
lv_obj_t * ui_EggButton = NULL;
lv_obj_t * ui_EasterEggResult = NULL;
// event funtions
void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_EasterButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setEasterEgg(e);
    }
}

void ui_event_EggButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setEasterEgg(e);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container6 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, lv_pct(100));
    lv_obj_set_height(ui_Container6, lv_pct(100));
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container8 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, lv_pct(20));
    lv_obj_set_height(ui_Container8, lv_pct(100));
    lv_obj_set_x(ui_Container8, 3);
    lv_obj_set_y(ui_Container8, 0);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button7 = lv_btn_create(ui_Container8);
    lv_obj_set_width(ui_Button7, lv_pct(98));
    lv_obj_set_height(ui_Button7, lv_pct(20));
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0xFF7474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button7, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button7, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Schijners");

    ui_Button4 = lv_btn_create(ui_Container8);
    lv_obj_set_width(ui_Button4, lv_pct(98));
    lv_obj_set_height(ui_Button4, lv_pct(20));
    lv_obj_set_x(ui_Button4, 1);
    lv_obj_set_y(ui_Button4, -1);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFF7474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button4, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Console	");

    ui_Container2 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, lv_pct(80));
    lv_obj_set_height(ui_Container2, lv_pct(100));
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Container2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lantern11Button = lv_btn_create(ui_Container2);
    lv_obj_set_height(ui_Lantern11Button, 148);
    lv_obj_set_width(ui_Lantern11Button, lv_pct(20));
    lv_obj_set_x(ui_Lantern11Button, -2);
    lv_obj_set_y(ui_Lantern11Button, -1);
    lv_obj_set_align(ui_Lantern11Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern11Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Lantern11Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lantern11Button, lv_color_hex(0x9CA3AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lantern11Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lantern11Button, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lantern11Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lantern11Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lantern11Label = lv_label_create(ui_Lantern11Button);
    lv_obj_set_width(ui_Lantern11Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lantern11Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Lantern11Label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Lantern11Label, "Lantaarn 11");
    lv_obj_set_style_text_color(ui_Lantern11Label, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lantern11Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network11Icon = lv_img_create(ui_Lantern11Button);
    lv_img_set_src(ui_Network11Icon, &ui_img_wifi_disabled_png);
    lv_obj_set_width(ui_Network11Icon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Network11Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Network11Icon, -10);
    lv_obj_set_y(ui_Network11Icon, 0);
    lv_obj_add_flag(ui_Network11Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Network11Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery11Icon = lv_img_create(ui_Lantern11Button);
    lv_img_set_src(ui_Battery11Icon, &ui_img_battery_disabled_png);
    lv_obj_set_width(ui_Battery11Icon, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Battery11Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Battery11Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery11Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery11Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern11Icon = lv_img_create(ui_Lantern11Button);
    lv_img_set_src(ui_Lantern11Icon, &ui_img_lantern_disabled_png);
    lv_obj_set_width(ui_Lantern11Icon, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Lantern11Icon, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_align(ui_Lantern11Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern11Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Lantern11Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Lantern11Icon, 255);

    ui_Lantern12Button = lv_btn_create(ui_Container2);
    lv_obj_set_height(ui_Lantern12Button, 148);
    lv_obj_set_width(ui_Lantern12Button, lv_pct(20));
    lv_obj_set_x(ui_Lantern12Button, 3);
    lv_obj_set_y(ui_Lantern12Button, 0);
    lv_obj_set_align(ui_Lantern12Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern12Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Lantern12Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lantern12Button, lv_color_hex(0x22C55E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lantern12Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lantern12Button, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lantern12Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lantern12Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lantern12Label = lv_label_create(ui_Lantern12Button);
    lv_obj_set_width(ui_Lantern12Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lantern12Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Lantern12Label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Lantern12Label, "Lantaarn 12");
    lv_obj_set_style_text_color(ui_Lantern12Label, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lantern12Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network12Icon = lv_img_create(ui_Lantern12Button);
    lv_img_set_src(ui_Network12Icon, &ui_img_wifi_0_20_png);
    lv_obj_set_width(ui_Network12Icon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Network12Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Network12Icon, -10);
    lv_obj_set_y(ui_Network12Icon, 0);
    lv_obj_add_flag(ui_Network12Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Network12Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery12Icon = lv_img_create(ui_Lantern12Button);
    lv_img_set_src(ui_Battery12Icon, &ui_img_battery_empty_png);
    lv_obj_set_width(ui_Battery12Icon, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Battery12Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Battery12Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery12Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery12Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern12Icon = lv_img_create(ui_Lantern12Button);
    lv_img_set_src(ui_Lantern12Icon, &ui_img_lantern_off_png);
    lv_obj_set_width(ui_Lantern12Icon, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Lantern12Icon, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_align(ui_Lantern12Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern12Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Lantern12Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Lantern12Icon, 255);

    ui_Lantern13Button = lv_btn_create(ui_Container2);
    lv_obj_set_height(ui_Lantern13Button, 148);
    lv_obj_set_width(ui_Lantern13Button, lv_pct(20));
    lv_obj_set_x(ui_Lantern13Button, -1);
    lv_obj_set_y(ui_Lantern13Button, 0);
    lv_obj_set_align(ui_Lantern13Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern13Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Lantern13Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lantern13Button, lv_color_hex(0xDDDDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lantern13Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lantern13Button, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lantern13Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lantern13Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lantern13Label = lv_label_create(ui_Lantern13Button);
    lv_obj_set_width(ui_Lantern13Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lantern13Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Lantern13Label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Lantern13Label, "Lantaarn 13");
    lv_obj_set_style_text_color(ui_Lantern13Label, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lantern13Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network13Icon = lv_img_create(ui_Lantern13Button);
    lv_img_set_src(ui_Network13Icon, &ui_img_wifi_20_40_png);
    lv_obj_set_width(ui_Network13Icon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Network13Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Network13Icon, -10);
    lv_obj_set_y(ui_Network13Icon, 0);
    lv_obj_add_flag(ui_Network13Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Network13Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery13Icon = lv_img_create(ui_Lantern13Button);
    lv_img_set_src(ui_Battery13Icon, &ui_img_battery_0_25_png);
    lv_obj_set_width(ui_Battery13Icon, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Battery13Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Battery13Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery13Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery13Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern13Icon = lv_img_create(ui_Lantern13Button);
    lv_img_set_src(ui_Lantern13Icon, &ui_img_lantern_on_png);
    lv_obj_set_width(ui_Lantern13Icon, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Lantern13Icon, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_align(ui_Lantern13Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern13Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Lantern13Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern14Button = lv_btn_create(ui_Container2);
    lv_obj_set_height(ui_Lantern14Button, 148);
    lv_obj_set_width(ui_Lantern14Button, lv_pct(20));
    lv_obj_set_x(ui_Lantern14Button, -1);
    lv_obj_set_y(ui_Lantern14Button, 0);
    lv_obj_set_align(ui_Lantern14Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern14Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Lantern14Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lantern14Button, lv_color_hex(0x22C55E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lantern14Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lantern14Button, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lantern14Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lantern14Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lantern14Label = lv_label_create(ui_Lantern14Button);
    lv_obj_set_width(ui_Lantern14Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lantern14Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Lantern14Label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Lantern14Label, "Lantaarn 14");
    lv_obj_set_style_text_color(ui_Lantern14Label, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lantern14Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network14Icon = lv_img_create(ui_Lantern14Button);
    lv_img_set_src(ui_Network14Icon, &ui_img_wifi_40_60_png);
    lv_obj_set_width(ui_Network14Icon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Network14Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Network14Icon, -10);
    lv_obj_set_y(ui_Network14Icon, 0);
    lv_obj_add_flag(ui_Network14Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Network14Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery14Icon = lv_img_create(ui_Lantern14Button);
    lv_img_set_src(ui_Battery14Icon, &ui_img_battery_25_50_png);
    lv_obj_set_width(ui_Battery14Icon, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Battery14Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Battery14Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery14Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery14Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern14Icon = lv_img_create(ui_Lantern14Button);
    lv_img_set_src(ui_Lantern14Icon, &ui_img_lantern_on_png);
    lv_obj_set_width(ui_Lantern14Icon, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Lantern14Icon, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_align(ui_Lantern14Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern14Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Lantern14Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern15Button = lv_btn_create(ui_Container2);
    lv_obj_set_height(ui_Lantern15Button, 148);
    lv_obj_set_width(ui_Lantern15Button, lv_pct(20));
    lv_obj_set_x(ui_Lantern15Button, -1);
    lv_obj_set_y(ui_Lantern15Button, 0);
    lv_obj_set_align(ui_Lantern15Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern15Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Lantern15Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lantern15Button, lv_color_hex(0x22C55E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lantern15Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lantern15Button, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lantern15Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lantern15Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lantern15Label = lv_label_create(ui_Lantern15Button);
    lv_obj_set_width(ui_Lantern15Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lantern15Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Lantern15Label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Lantern15Label, "Lantaarn 15");
    lv_obj_set_style_text_color(ui_Lantern15Label, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lantern15Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network15Icon = lv_img_create(ui_Lantern15Button);
    lv_img_set_src(ui_Network15Icon, &ui_img_wifi_60_80_png);
    lv_obj_set_width(ui_Network15Icon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Network15Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Network15Icon, -10);
    lv_obj_set_y(ui_Network15Icon, 0);
    lv_obj_add_flag(ui_Network15Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Network15Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery15Icon = lv_img_create(ui_Lantern15Button);
    lv_img_set_src(ui_Battery15Icon, &ui_img_battery_50_75_png);
    lv_obj_set_width(ui_Battery15Icon, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Battery15Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Battery15Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery15Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery15Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern15Icon = lv_img_create(ui_Lantern15Button);
    lv_img_set_src(ui_Lantern15Icon, &ui_img_lantern_off_png);
    lv_obj_set_width(ui_Lantern15Icon, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Lantern15Icon, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_align(ui_Lantern15Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern15Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Lantern15Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EasterButton = lv_btn_create(ui_Container2);
    lv_obj_set_height(ui_EasterButton, 148);
    lv_obj_set_width(ui_EasterButton, lv_pct(20));
    lv_obj_set_x(ui_EasterButton, 0);
    lv_obj_set_y(ui_EasterButton, -1);
    lv_obj_set_align(ui_EasterButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EasterButton, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_EasterButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_EasterButton, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EasterButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_EasterButton, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EasterButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_EasterButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EggButton = lv_btn_create(ui_Container2);
    lv_obj_set_height(ui_EggButton, 148);
    lv_obj_set_width(ui_EggButton, lv_pct(20));
    lv_obj_set_x(ui_EggButton, 0);
    lv_obj_set_y(ui_EggButton, -1);
    lv_obj_set_align(ui_EggButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EggButton, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_EggButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_EggButton, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EggButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_EggButton, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EggButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_EggButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EasterEggResult = lv_label_create(ui_EggButton);
    lv_obj_set_width(ui_EasterEggResult, 150);
    lv_obj_set_height(ui_EasterEggResult, 250);
    lv_obj_set_align(ui_EasterEggResult, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EasterEggResult, "");
    lv_obj_set_style_bg_color(ui_EasterEggResult, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EasterEggResult, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_EasterButton, ui_event_EasterButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_EggButton, ui_event_EggButton, LV_EVENT_ALL, NULL);
    uic_Screen2 = ui_Screen2;
    uic_Container2 = ui_Container2;
    uic_Lantern11Button = ui_Lantern11Button;
    uic_Lantern11Label = ui_Lantern11Label;
    uic_Network11Icon = ui_Network11Icon;
    uic_Battery11Icon = ui_Battery11Icon;
    uic_Lantern11Icon = ui_Lantern11Icon;
    uic_Lantern12Button = ui_Lantern12Button;
    uic_Lantern12Label = ui_Lantern12Label;
    uic_Network12Icon = ui_Network12Icon;
    uic_Battery12Icon = ui_Battery12Icon;
    uic_Lantern12Icon = ui_Lantern12Icon;
    uic_Lantern13Button = ui_Lantern13Button;
    uic_Lantern13Label = ui_Lantern13Label;
    uic_Network13Icon = ui_Network13Icon;
    uic_Battery13Icon = ui_Battery13Icon;
    uic_Lantern13Icon = ui_Lantern13Icon;
    uic_Lantern14Button = ui_Lantern14Button;
    uic_Lantern14Label = ui_Lantern14Label;
    uic_Network14Icon = ui_Network14Icon;
    uic_Battery14Icon = ui_Battery14Icon;
    uic_Lantern14Icon = ui_Lantern14Icon;
    uic_Lantern15Button = ui_Lantern15Button;
    uic_Lantern15Label = ui_Lantern15Label;
    uic_Network15Icon = ui_Network15Icon;
    uic_Battery15Icon = ui_Battery15Icon;
    uic_Lantern15Icon = ui_Lantern15Icon;
    uic_EasterButton = ui_EasterButton;
    uic_EasterEggResult = ui_EasterEggResult;

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    uic_Screen2 = NULL;
    ui_Screen2 = NULL;
    ui_Container6 = NULL;
    ui_Container8 = NULL;
    ui_Button7 = NULL;
    ui_Label6 = NULL;
    ui_Button4 = NULL;
    ui_Label7 = NULL;
    uic_Container2 = NULL;
    ui_Container2 = NULL;
    uic_Lantern11Button = NULL;
    ui_Lantern11Button = NULL;
    uic_Lantern11Label = NULL;
    ui_Lantern11Label = NULL;
    uic_Network11Icon = NULL;
    ui_Network11Icon = NULL;
    uic_Battery11Icon = NULL;
    ui_Battery11Icon = NULL;
    uic_Lantern11Icon = NULL;
    ui_Lantern11Icon = NULL;
    uic_Lantern12Button = NULL;
    ui_Lantern12Button = NULL;
    uic_Lantern12Label = NULL;
    ui_Lantern12Label = NULL;
    uic_Network12Icon = NULL;
    ui_Network12Icon = NULL;
    uic_Battery12Icon = NULL;
    ui_Battery12Icon = NULL;
    uic_Lantern12Icon = NULL;
    ui_Lantern12Icon = NULL;
    uic_Lantern13Button = NULL;
    ui_Lantern13Button = NULL;
    uic_Lantern13Label = NULL;
    ui_Lantern13Label = NULL;
    uic_Network13Icon = NULL;
    ui_Network13Icon = NULL;
    uic_Battery13Icon = NULL;
    ui_Battery13Icon = NULL;
    uic_Lantern13Icon = NULL;
    ui_Lantern13Icon = NULL;
    uic_Lantern14Button = NULL;
    ui_Lantern14Button = NULL;
    uic_Lantern14Label = NULL;
    ui_Lantern14Label = NULL;
    uic_Network14Icon = NULL;
    ui_Network14Icon = NULL;
    uic_Battery14Icon = NULL;
    ui_Battery14Icon = NULL;
    uic_Lantern14Icon = NULL;
    ui_Lantern14Icon = NULL;
    uic_Lantern15Button = NULL;
    ui_Lantern15Button = NULL;
    uic_Lantern15Label = NULL;
    ui_Lantern15Label = NULL;
    uic_Network15Icon = NULL;
    ui_Network15Icon = NULL;
    uic_Battery15Icon = NULL;
    ui_Battery15Icon = NULL;
    uic_Lantern15Icon = NULL;
    ui_Lantern15Icon = NULL;
    uic_EasterButton = NULL;
    ui_EasterButton = NULL;
    ui_EggButton = NULL;
    uic_EasterEggResult = NULL;
    ui_EasterEggResult = NULL;

}
