// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ArcaFace

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Container4;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Lux1Button;
extern lv_obj_t * ui_Lux1Label;
extern lv_obj_t * ui_Network1Icon;
extern lv_obj_t * ui_Battery1Icon;
extern void ui_event_Lux1Icon(lv_event_t * e);
extern lv_obj_t * ui_Lux1Icon;
extern void ui_event_Colorwheel1(lv_event_t * e);
extern lv_obj_t * ui_Colorwheel1;
extern void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Lux2Button;
extern lv_obj_t * ui_Lux2Label;
extern lv_obj_t * ui_Network2Icon;
extern lv_obj_t * ui_Battery2Icon;
extern void ui_event_Lux2Icon(lv_event_t * e);
extern lv_obj_t * ui_Lux2Icon;
extern void ui_event_Colorwheel2(lv_event_t * e);
extern lv_obj_t * ui_Colorwheel2;
extern void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Lux3Button;
extern lv_obj_t * ui_Lux3Label;
extern lv_obj_t * ui_Network3Icon;
extern lv_obj_t * ui_Battery3Icon;
extern void ui_event_Lux3Icon(lv_event_t * e);
extern lv_obj_t * ui_Lux3Icon;
extern void ui_event_Colorwheel3(lv_event_t * e);
extern lv_obj_t * ui_Colorwheel3;
extern void ui_event_Slider3(lv_event_t * e);
extern lv_obj_t * ui_Slider3;
extern lv_obj_t * ui_Lux4Button;
extern lv_obj_t * ui_Lux4Label;
extern lv_obj_t * ui_Network4Icon;
extern lv_obj_t * ui_Battery4Icon;
extern void ui_event_Lux4Icon(lv_event_t * e);
extern lv_obj_t * ui_Lux4Icon;
extern void ui_event_Colorwheel4(lv_event_t * e);
extern lv_obj_t * ui_Colorwheel4;
extern void ui_event_Slider4(lv_event_t * e);
extern lv_obj_t * ui_Slider4;
extern lv_obj_t * ui_Lux5Button;
extern lv_obj_t * ui_Lux5Label;
extern lv_obj_t * ui_Network5Icon;
extern lv_obj_t * ui_Battery5Icon;
extern void ui_event_Lux5Icon(lv_event_t * e);
extern lv_obj_t * ui_Lux5Icon;
extern void ui_event_Colorwheel5(lv_event_t * e);
extern lv_obj_t * ui_Colorwheel5;
extern void ui_event_Slider5(lv_event_t * e);
extern lv_obj_t * ui_Slider5;
extern lv_obj_t * ui_Lux6Button;
extern lv_obj_t * ui_Lux6Label;
extern lv_obj_t * ui_Network6Icon;
extern lv_obj_t * ui_Battery6Icon;
extern void ui_event_Lux6Icon(lv_event_t * e);
extern lv_obj_t * ui_Lux6Icon;
extern void ui_event_Colorwheel6(lv_event_t * e);
extern lv_obj_t * ui_Colorwheel6;
extern void ui_event_Slider6(lv_event_t * e);
extern lv_obj_t * ui_Slider6;
extern lv_obj_t * ui_Lux7Button;
extern lv_obj_t * ui_Lux7Label;
extern lv_obj_t * ui_Network7Icon;
extern lv_obj_t * ui_Battery7Icon;
extern void ui_event_Lux7Icon(lv_event_t * e);
extern lv_obj_t * ui_Lux7Icon;
extern void ui_event_Colorwheel7(lv_event_t * e);
extern lv_obj_t * ui_Colorwheel7;
extern void ui_event_Slider7(lv_event_t * e);
extern lv_obj_t * ui_Slider7;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen1;
extern lv_obj_t * uic_Lux1Button;
extern lv_obj_t * uic_Lux1Label;
extern lv_obj_t * uic_Network1Icon;
extern lv_obj_t * uic_Battery1Icon;
extern lv_obj_t * uic_Lux1Icon;
extern lv_obj_t * uic_Colorwheel1;
extern lv_obj_t * uic_Slider1;
extern lv_obj_t * uic_Lux2Button;
extern lv_obj_t * uic_Lux2Label;
extern lv_obj_t * uic_Network2Icon;
extern lv_obj_t * uic_Battery2Icon;
extern lv_obj_t * uic_Lux2Icon;
extern lv_obj_t * uic_Colorwheel2;
extern lv_obj_t * uic_Slider2;
extern lv_obj_t * uic_Lux3Button;
extern lv_obj_t * uic_Lux3Label;
extern lv_obj_t * uic_Network3Icon;
extern lv_obj_t * uic_Battery3Icon;
extern lv_obj_t * uic_Lux3Icon;
extern lv_obj_t * uic_Colorwheel3;
extern lv_obj_t * uic_Slider3;
extern lv_obj_t * uic_Lux4Button;
extern lv_obj_t * uic_Lux4Label;
extern lv_obj_t * uic_Network4Icon;
extern lv_obj_t * uic_Battery4Icon;
extern lv_obj_t * uic_Lux4Icon;
extern lv_obj_t * uic_Colorwheel4;
extern lv_obj_t * uic_Slider4;
extern lv_obj_t * uic_Lux5Button;
extern lv_obj_t * uic_Lux5Label;
extern lv_obj_t * uic_Network5Icon;
extern lv_obj_t * uic_Battery5Icon;
extern lv_obj_t * uic_Lux5Icon;
extern lv_obj_t * uic_Colorwheel5;
extern lv_obj_t * uic_Slider5;
extern lv_obj_t * uic_Lux6Button;
extern lv_obj_t * uic_Lux6Label;
extern lv_obj_t * uic_Network6Icon;
extern lv_obj_t * uic_Battery6Icon;
extern lv_obj_t * uic_Lux6Icon;
extern lv_obj_t * uic_Colorwheel6;
extern lv_obj_t * uic_Slider6;
extern lv_obj_t * uic_Lux7Button;
extern lv_obj_t * uic_Lux7Label;
extern lv_obj_t * uic_Network7Icon;
extern lv_obj_t * uic_Battery7Icon;
extern lv_obj_t * uic_Lux7Icon;
extern lv_obj_t * uic_Colorwheel7;
extern lv_obj_t * uic_Slider7;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

