// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ArcaFace

#include "../ui.h"

lv_obj_t * uic_Console;
lv_obj_t * uic_LuxConsoleButton;
lv_obj_t * uic_Container3;
lv_obj_t * uic_Screen3;
lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_LuxConsoleButton = NULL;
lv_obj_t * ui_Console = NULL;
// event funtions
void ui_event_Screen3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Screen3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_Container3 = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, lv_pct(100));
    lv_obj_set_height(ui_Container3, lv_pct(100));
    lv_obj_set_x(ui_Container3, -229);
    lv_obj_set_y(ui_Container3, -92);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LuxConsoleButton = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_LuxConsoleButton, 822);
    lv_obj_set_height(ui_LuxConsoleButton, 595);
    lv_obj_set_x(ui_LuxConsoleButton, -475);
    lv_obj_set_y(ui_LuxConsoleButton, -30);
    lv_obj_set_align(ui_LuxConsoleButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LuxConsoleButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LuxConsoleButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LuxConsoleButton, lv_color_hex(0x9CA3AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LuxConsoleButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LuxConsoleButton, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LuxConsoleButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LuxConsoleButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Console = lv_label_create(ui_LuxConsoleButton);
    lv_obj_set_width(ui_Console, lv_pct(100));
    lv_obj_set_height(ui_Console, lv_pct(100));
    lv_obj_set_align(ui_Console, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Console, "Console");
    lv_obj_set_style_text_color(ui_Console, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Console, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);
    uic_Screen3 = ui_Screen3;
    uic_Container3 = ui_Container3;
    uic_LuxConsoleButton = ui_LuxConsoleButton;
    uic_Console = ui_Console;

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    uic_Screen3 = NULL;
    ui_Screen3 = NULL;
    uic_Container3 = NULL;
    ui_Container3 = NULL;
    uic_LuxConsoleButton = NULL;
    ui_LuxConsoleButton = NULL;
    uic_Console = NULL;
    ui_Console = NULL;

}
