// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ArcaFace

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_Lux5Button2 = NULL;
lv_obj_t * ui_Lux5Label2 = NULL;
lv_obj_t * ui_Network5Icon2 = NULL;
lv_obj_t * ui_Battery5Icon2 = NULL;
lv_obj_t * ui_Lux5Icon2 = NULL;
lv_obj_t * ui_Colorwheel6 = NULL;
lv_obj_t * ui_Slider2 = NULL;
// event funtions
void ui_event_Lux5Icon2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setToBlack4(e);
    }
}

void ui_event_Colorwheel6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        setColorFromScreen4(e);
    }
}

void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        setBrightness4(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, lv_pct(100));
    lv_obj_set_height(ui_Container1, lv_pct(100));
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, lv_pct(20));
    lv_obj_set_height(ui_Container4, lv_pct(100));
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_Container4);
    lv_obj_set_width(ui_Button1, lv_pct(98));
    lv_obj_set_height(ui_Button1, lv_pct(20));
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFF7474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button1, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, lv_pct(80));
    lv_obj_set_height(ui_Container5, lv_pct(100));
    lv_obj_set_x(ui_Container5, 11);
    lv_obj_set_y(ui_Container5, 119);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lux5Button2 = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_Lux5Button2, lv_pct(33));
    lv_obj_set_height(ui_Lux5Button2, lv_pct(50));
    lv_obj_set_align(ui_Lux5Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lux5Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Lux5Button2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lux5Button2, lv_color_hex(0x9CA3AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lux5Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lux5Button2, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lux5Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lux5Button2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lux5Label2 = lv_label_create(ui_Lux5Button2);
    lv_obj_set_width(ui_Lux5Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lux5Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Lux5Label2, -13);
    lv_obj_set_y(ui_Lux5Label2, -252);
    lv_obj_set_align(ui_Lux5Label2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Lux5Label2, "Straler 4");
    lv_obj_set_style_text_color(ui_Lux5Label2, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lux5Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network5Icon2 = lv_img_create(ui_Lux5Button2);
    lv_img_set_src(ui_Network5Icon2, &ui_img_wifi_disabled_png);
    lv_obj_set_width(ui_Network5Icon2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Network5Icon2, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Network5Icon2, -30);
    lv_obj_set_y(ui_Network5Icon2, 0);
    lv_obj_set_align(ui_Network5Icon2, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Network5Icon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Network5Icon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery5Icon2 = lv_img_create(ui_Lux5Button2);
    lv_img_set_src(ui_Battery5Icon2, &ui_img_battery_disabled_png);
    lv_obj_set_width(ui_Battery5Icon2, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Battery5Icon2, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Battery5Icon2, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery5Icon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery5Icon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lux5Icon2 = lv_img_create(ui_Lux5Button2);
    lv_img_set_src(ui_Lux5Icon2, &ui_img_gem_disabled_png);
    lv_obj_set_width(ui_Lux5Icon2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Lux5Icon2, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Lux5Icon2, -100);
    lv_obj_set_y(ui_Lux5Icon2, -22);
    lv_obj_set_align(ui_Lux5Icon2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Lux5Icon2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Lux5Icon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Lux5Icon2, 150);

    ui_Colorwheel6 = lv_colorwheel_create(ui_Lux5Button2, true);
    lv_colorwheel_set_mode_fixed(ui_Colorwheel6, true);
    lv_obj_set_width(ui_Colorwheel6, 180);
    lv_obj_set_height(ui_Colorwheel6, 180);
    lv_obj_set_x(ui_Colorwheel6, 15);
    lv_obj_set_y(ui_Colorwheel6, -20);
    lv_obj_set_align(ui_Colorwheel6, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_blend_mode(ui_Colorwheel6, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Colorwheel6, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_Lux5Button2);
    lv_slider_set_value(ui_Slider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_Slider2, 20);
    lv_obj_set_width(ui_Slider2, lv_pct(96));
    lv_obj_set_x(ui_Slider2, 0);
    lv_obj_set_y(ui_Slider2, 120);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_radius(ui_Slider2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider2, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Slider2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Slider2, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Slider2, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slider2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Slider2, 4, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Lux5Icon2, ui_event_Lux5Icon2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Colorwheel6, ui_event_Colorwheel6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Container1 = NULL;
    ui_Container4 = NULL;
    ui_Button1 = NULL;
    ui_Container5 = NULL;
    ui_Lux5Button2 = NULL;
    ui_Lux5Label2 = NULL;
    ui_Network5Icon2 = NULL;
    ui_Battery5Icon2 = NULL;
    ui_Lux5Icon2 = NULL;
    ui_Colorwheel6 = NULL;
    ui_Slider2 = NULL;

}
