// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ArcaFace

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Container8;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label6;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Lantern11Button;
extern lv_obj_t * ui_Lantern11Label;
extern lv_obj_t * ui_Network11Icon;
extern lv_obj_t * ui_Battery11Icon;
extern lv_obj_t * ui_Lantern11Icon;
extern lv_obj_t * ui_Lantern12Button;
extern lv_obj_t * ui_Lantern12Label;
extern lv_obj_t * ui_Network12Icon;
extern lv_obj_t * ui_Battery12Icon;
extern lv_obj_t * ui_Lantern12Icon;
extern lv_obj_t * ui_Lantern13Button;
extern lv_obj_t * ui_Lantern13Label;
extern lv_obj_t * ui_Network13Icon;
extern lv_obj_t * ui_Battery13Icon;
extern lv_obj_t * ui_Lantern13Icon;
extern lv_obj_t * ui_Lantern14Button;
extern lv_obj_t * ui_Lantern14Label;
extern lv_obj_t * ui_Network14Icon;
extern lv_obj_t * ui_Battery14Icon;
extern lv_obj_t * ui_Lantern14Icon;
extern lv_obj_t * ui_Lantern15Button;
extern lv_obj_t * ui_Lantern15Label;
extern lv_obj_t * ui_Network15Icon;
extern lv_obj_t * ui_Battery15Icon;
extern lv_obj_t * ui_Lantern15Icon;
extern lv_obj_t * ui_Lantern16Button;
extern lv_obj_t * ui_Lantern16Label;
extern lv_obj_t * ui_Network16Icon;
extern lv_obj_t * ui_Battery16Icon;
extern lv_obj_t * ui_Lantern16Icon;
extern lv_obj_t * ui_Lantern19Button;
extern lv_obj_t * ui_Lantern19Label;
extern lv_obj_t * ui_Network19Icon;
extern lv_obj_t * ui_Battery19Icon;
extern lv_obj_t * ui_Lantern19Icon;
extern lv_obj_t * ui_Lantern20Button;
extern lv_obj_t * ui_Lantern20Label;
extern lv_obj_t * ui_Network20Icon;
extern lv_obj_t * ui_Battery20Icon;
extern lv_obj_t * ui_Lantern20Icon;
extern lv_obj_t * ui_Lantern21Button;
extern lv_obj_t * ui_Lantern21Label;
extern lv_obj_t * ui_Network21Icon;
extern lv_obj_t * ui_Battery21Icon;
extern lv_obj_t * ui_Lantern21Icon;
extern lv_obj_t * ui_Lantern22Button;
extern lv_obj_t * ui_Lantern22Label;
extern lv_obj_t * ui_Network22Icon;
extern lv_obj_t * ui_Battery22Icon;
extern lv_obj_t * ui_Lantern22Icon;
extern lv_obj_t * ui_Lantern23Button;
extern lv_obj_t * ui_Lantern23Label;
extern lv_obj_t * ui_Network23Icon;
extern lv_obj_t * ui_Battery23Icon;
extern lv_obj_t * ui_Lantern23Icon;
extern lv_obj_t * ui_Lantern24Button;
extern lv_obj_t * ui_Lantern24Label;
extern lv_obj_t * ui_Network24Icon;
extern lv_obj_t * ui_Battery24Icon;
extern lv_obj_t * ui_Lantern24Icon;
extern void ui_event_EasterButton(lv_event_t * e);
extern lv_obj_t * ui_EasterButton;
extern void ui_event_EggButton(lv_event_t * e);
extern lv_obj_t * ui_EggButton;
extern lv_obj_t * ui_EasterEggResult;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen2;
extern lv_obj_t * uic_Container2;
extern lv_obj_t * uic_Lantern11Button;
extern lv_obj_t * uic_Lantern11Label;
extern lv_obj_t * uic_Network11Icon;
extern lv_obj_t * uic_Battery11Icon;
extern lv_obj_t * uic_Lantern11Icon;
extern lv_obj_t * uic_Lantern12Button;
extern lv_obj_t * uic_Lantern12Label;
extern lv_obj_t * uic_Network12Icon;
extern lv_obj_t * uic_Battery12Icon;
extern lv_obj_t * uic_Lantern12Icon;
extern lv_obj_t * uic_Lantern13Button;
extern lv_obj_t * uic_Lantern13Label;
extern lv_obj_t * uic_Network13Icon;
extern lv_obj_t * uic_Battery13Icon;
extern lv_obj_t * uic_Lantern13Icon;
extern lv_obj_t * uic_Lantern14Button;
extern lv_obj_t * uic_Lantern14Label;
extern lv_obj_t * uic_Network14Icon;
extern lv_obj_t * uic_Battery14Icon;
extern lv_obj_t * uic_Lantern14Icon;
extern lv_obj_t * uic_Lantern15Button;
extern lv_obj_t * uic_Lantern15Label;
extern lv_obj_t * uic_Network15Icon;
extern lv_obj_t * uic_Battery15Icon;
extern lv_obj_t * uic_Lantern15Icon;
extern lv_obj_t * uic_Lantern16Button;
extern lv_obj_t * uic_Lantern16Label;
extern lv_obj_t * uic_Network16Icon;
extern lv_obj_t * uic_Battery16Icon;
extern lv_obj_t * uic_Lantern16Icon;
extern lv_obj_t * uic_Lantern19Button;
extern lv_obj_t * uic_Lantern19Label;
extern lv_obj_t * uic_Network19Icon;
extern lv_obj_t * uic_Battery19Icon;
extern lv_obj_t * uic_Lantern19Icon;
extern lv_obj_t * uic_Lantern20Button;
extern lv_obj_t * uic_Lantern20Label;
extern lv_obj_t * uic_Network20Icon;
extern lv_obj_t * uic_Battery20Icon;
extern lv_obj_t * uic_Lantern20Icon;
extern lv_obj_t * uic_Lantern21Button;
extern lv_obj_t * uic_Lantern21Label;
extern lv_obj_t * uic_Network21Icon;
extern lv_obj_t * uic_Battery21Icon;
extern lv_obj_t * uic_Lantern21Icon;
extern lv_obj_t * uic_Lantern22Button;
extern lv_obj_t * uic_Lantern22Label;
extern lv_obj_t * uic_Network22Icon;
extern lv_obj_t * uic_Battery22Icon;
extern lv_obj_t * uic_Lantern22Icon;
extern lv_obj_t * uic_Lantern23Button;
extern lv_obj_t * uic_Lantern23Label;
extern lv_obj_t * uic_Network23Icon;
extern lv_obj_t * uic_Battery23Icon;
extern lv_obj_t * uic_Lantern23Icon;
extern lv_obj_t * uic_Lantern24Button;
extern lv_obj_t * uic_Lantern24Label;
extern lv_obj_t * uic_Network24Icon;
extern lv_obj_t * uic_Battery24Icon;
extern lv_obj_t * uic_Lantern24Icon;
extern lv_obj_t * uic_EasterButton;
extern lv_obj_t * uic_EasterEggResult;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

