// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ArcaFace

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Container4;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Lux1Button;
extern lv_obj_t * ui_Lux1Label;
extern lv_obj_t * ui_Network1Icon;
extern lv_obj_t * ui_Battery1Icon;
extern void ui_event_Colorwheel1(lv_event_t * e);
extern lv_obj_t * ui_Colorwheel1;
extern void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Lux2Button;
extern lv_obj_t * ui_Lux2Label;
extern lv_obj_t * ui_Network2Icon;
extern lv_obj_t * ui_Battery2Icon;
extern void ui_event_Colorwheel2(lv_event_t * e);
extern lv_obj_t * ui_Colorwheel2;
extern void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen1;
extern lv_obj_t * uic_Lux1Button;
extern lv_obj_t * uic_Lux1Label;
extern lv_obj_t * uic_Network1Icon;
extern lv_obj_t * uic_Battery1Icon;
extern lv_obj_t * uic_Colorwheel1;
extern lv_obj_t * uic_Slider1;
extern lv_obj_t * uic_Lux2Button;
extern lv_obj_t * uic_Lux2Label;
extern lv_obj_t * uic_Network2Icon;
extern lv_obj_t * uic_Battery2Icon;
extern lv_obj_t * uic_Colorwheel2;
extern lv_obj_t * uic_Slider2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

