// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ArcaFace

#include "../ui.h"

lv_obj_t * uic_EasterEggResult;
lv_obj_t * uic_GemGlyph71OutButtonLabel;
lv_obj_t * uic_GemGlyph71OutButton;
lv_obj_t * uic_GemGlyph71Icon;
lv_obj_t * uic_GemGlyph71Label;
lv_obj_t * uic_GemGlyph71Button;
lv_obj_t * uic_EasterButton;
lv_obj_t * uic_Colorwheel4;
lv_obj_t * uic_Lux4Icon;
lv_obj_t * uic_Battery4Icon;
lv_obj_t * uic_Network4Icon;
lv_obj_t * uic_Lux4Label;
lv_obj_t * uic_Lux4Button;
lv_obj_t * uic_Colorwheel3;
lv_obj_t * uic_Lux3Icon;
lv_obj_t * uic_Battery3Icon;
lv_obj_t * uic_Network3Icon;
lv_obj_t * uic_Lux3Label;
lv_obj_t * uic_Lux3Button;
lv_obj_t * uic_Colorwheel2;
lv_obj_t * uic_Lux2Icon;
lv_obj_t * uic_Battery2Icon;
lv_obj_t * uic_Network2Icon;
lv_obj_t * uic_Lux2Label;
lv_obj_t * uic_Lux2Button;
lv_obj_t * uic_Lantern24Icon;
lv_obj_t * uic_Battery24Icon;
lv_obj_t * uic_Network24Icon;
lv_obj_t * uic_Lantern24Label;
lv_obj_t * uic_Lantern24Button;
lv_obj_t * uic_Lantern23Icon;
lv_obj_t * uic_Battery23Icon;
lv_obj_t * uic_Network23Icon;
lv_obj_t * uic_Lantern23Label;
lv_obj_t * uic_Lantern23Button;
lv_obj_t * uic_Lantern22Icon;
lv_obj_t * uic_Battery22Icon;
lv_obj_t * uic_Network22Icon;
lv_obj_t * uic_Lantern22Label;
lv_obj_t * uic_Lantern22Button;
lv_obj_t * uic_Lantern21Icon;
lv_obj_t * uic_Battery21Icon;
lv_obj_t * uic_Network21Icon;
lv_obj_t * uic_Lantern21Label;
lv_obj_t * uic_Lantern21Button;
lv_obj_t * uic_Lantern20Icon;
lv_obj_t * uic_Battery20Icon;
lv_obj_t * uic_Network20Icon;
lv_obj_t * uic_Lantern20Label;
lv_obj_t * uic_Lantern20Button;
lv_obj_t * uic_Lantern19Icon;
lv_obj_t * uic_Battery19Icon;
lv_obj_t * uic_Network19Icon;
lv_obj_t * uic_Lantern19Label;
lv_obj_t * uic_Lantern19Button;
lv_obj_t * uic_Lantern16Icon;
lv_obj_t * uic_Battery16Icon;
lv_obj_t * uic_Network16Icon;
lv_obj_t * uic_Lantern16Label;
lv_obj_t * uic_Lantern16Button;
lv_obj_t * uic_Lantern15Icon;
lv_obj_t * uic_Battery15Icon;
lv_obj_t * uic_Network15Icon;
lv_obj_t * uic_Lantern15Label;
lv_obj_t * uic_Lantern15Button;
lv_obj_t * uic_Lantern14Icon;
lv_obj_t * uic_Battery14Icon;
lv_obj_t * uic_Network14Icon;
lv_obj_t * uic_Lantern14Label;
lv_obj_t * uic_Lantern14Button;
lv_obj_t * uic_Lantern13Icon;
lv_obj_t * uic_Battery13Icon;
lv_obj_t * uic_Network13Icon;
lv_obj_t * uic_Lantern13Label;
lv_obj_t * uic_Lantern13Button;
lv_obj_t * uic_Lantern12Icon;
lv_obj_t * uic_Battery12Icon;
lv_obj_t * uic_Network12Icon;
lv_obj_t * uic_Lantern12Label;
lv_obj_t * uic_Lantern12Button;
lv_obj_t * uic_Lantern11Icon;
lv_obj_t * uic_Battery11Icon;
lv_obj_t * uic_Network11Icon;
lv_obj_t * uic_Lantern11Label;
lv_obj_t * uic_Lantern11Button;
lv_obj_t * uic_Screen2;
lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_ArcaButt1 = NULL;
lv_obj_t * ui_Lantern11Button = NULL;
lv_obj_t * ui_Lantern11Label = NULL;
lv_obj_t * ui_Network11Icon = NULL;
lv_obj_t * ui_Battery11Icon = NULL;
lv_obj_t * ui_Lantern11Icon = NULL;
lv_obj_t * ui_Lantern12Button = NULL;
lv_obj_t * ui_Lantern12Label = NULL;
lv_obj_t * ui_Network12Icon = NULL;
lv_obj_t * ui_Battery12Icon = NULL;
lv_obj_t * ui_Lantern12Icon = NULL;
lv_obj_t * ui_Lantern13Button = NULL;
lv_obj_t * ui_Lantern13Label = NULL;
lv_obj_t * ui_Network13Icon = NULL;
lv_obj_t * ui_Battery13Icon = NULL;
lv_obj_t * ui_Lantern13Icon = NULL;
lv_obj_t * ui_Lantern14Button = NULL;
lv_obj_t * ui_Lantern14Label = NULL;
lv_obj_t * ui_Network14Icon = NULL;
lv_obj_t * ui_Battery14Icon = NULL;
lv_obj_t * ui_Lantern14Icon = NULL;
lv_obj_t * ui_Lantern15Button = NULL;
lv_obj_t * ui_Lantern15Label = NULL;
lv_obj_t * ui_Network15Icon = NULL;
lv_obj_t * ui_Battery15Icon = NULL;
lv_obj_t * ui_Lantern15Icon = NULL;
lv_obj_t * ui_Lantern16Button = NULL;
lv_obj_t * ui_Lantern16Label = NULL;
lv_obj_t * ui_Network16Icon = NULL;
lv_obj_t * ui_Battery16Icon = NULL;
lv_obj_t * ui_Lantern16Icon = NULL;
lv_obj_t * ui_Lantern19Button = NULL;
lv_obj_t * ui_Lantern19Label = NULL;
lv_obj_t * ui_Network19Icon = NULL;
lv_obj_t * ui_Battery19Icon = NULL;
lv_obj_t * ui_Lantern19Icon = NULL;
lv_obj_t * ui_Lantern20Button = NULL;
lv_obj_t * ui_Lantern20Label = NULL;
lv_obj_t * ui_Network20Icon = NULL;
lv_obj_t * ui_Battery20Icon = NULL;
lv_obj_t * ui_Lantern20Icon = NULL;
lv_obj_t * ui_Lantern21Button = NULL;
lv_obj_t * ui_Lantern21Label = NULL;
lv_obj_t * ui_Network21Icon = NULL;
lv_obj_t * ui_Battery21Icon = NULL;
lv_obj_t * ui_Lantern21Icon = NULL;
lv_obj_t * ui_Lantern22Button = NULL;
lv_obj_t * ui_Lantern22Label = NULL;
lv_obj_t * ui_Network22Icon = NULL;
lv_obj_t * ui_Battery22Icon = NULL;
lv_obj_t * ui_Lantern22Icon = NULL;
lv_obj_t * ui_Lantern23Button = NULL;
lv_obj_t * ui_Lantern23Label = NULL;
lv_obj_t * ui_Network23Icon = NULL;
lv_obj_t * ui_Battery23Icon = NULL;
lv_obj_t * ui_Lantern23Icon = NULL;
lv_obj_t * ui_Lantern24Button = NULL;
lv_obj_t * ui_Lantern24Label = NULL;
lv_obj_t * ui_Network24Icon = NULL;
lv_obj_t * ui_Battery24Icon = NULL;
lv_obj_t * ui_Lantern24Icon = NULL;
lv_obj_t * ui_Lux2Button = NULL;
lv_obj_t * ui_Lux2Label = NULL;
lv_obj_t * ui_Network2Icon = NULL;
lv_obj_t * ui_Battery2Icon = NULL;
lv_obj_t * ui_Lux2Icon = NULL;
lv_obj_t * ui_Colorwheel2 = NULL;
lv_obj_t * ui_Lux3Button = NULL;
lv_obj_t * ui_Lux3Label = NULL;
lv_obj_t * ui_Network3Icon = NULL;
lv_obj_t * ui_Battery3Icon = NULL;
lv_obj_t * ui_Lux3Icon = NULL;
lv_obj_t * ui_Colorwheel3 = NULL;
lv_obj_t * ui_Lux4Button = NULL;
lv_obj_t * ui_Lux4Label = NULL;
lv_obj_t * ui_Network4Icon = NULL;
lv_obj_t * ui_Battery4Icon = NULL;
lv_obj_t * ui_Lux4Icon = NULL;
lv_obj_t * ui_Colorwheel4 = NULL;
lv_obj_t * ui_EasterButton = NULL;
lv_obj_t * ui_GemGlyph71Button = NULL;
lv_obj_t * ui_GemGlyph71Label = NULL;
lv_obj_t * ui_GemGlyph71Icon = NULL;
lv_obj_t * ui_GemGlyph71InButton = NULL;
lv_obj_t * ui_GemGlyph71InButtonLabel = NULL;
lv_obj_t * ui_GemGlyph71OutButton = NULL;
lv_obj_t * ui_GemGlyph71OutButtonLabel = NULL;
lv_obj_t * ui_EggButton = NULL;
lv_obj_t * ui_EasterEggResult = NULL;
// event funtions
void ui_event_Lux2Icon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setToBlack2(e);
    }
}

void ui_event_Colorwheel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        setColorFromScreen2(e);
    }
}

void ui_event_Lux3Icon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setToBlack3(e);
    }
}

void ui_event_Colorwheel3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        setColorFromScreen3(e);
    }
}

void ui_event_Lux4Icon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setToBlack4(e);
    }
}

void ui_event_Colorwheel4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        setColorFromScreen4(e);
    }
}

void ui_event_EasterButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setEasterEgg(e);
    }
}

void ui_event_GemGlyph71InButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        activateGolemInSequence(e);
    }
}

void ui_event_GemGlyph71OutButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        activateGolemOutSequence(e);
    }
}

void ui_event_EggButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setEasterEgg(e);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ArcaButt1 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_ArcaButt1);
    lv_obj_set_width(ui_ArcaButt1, lv_pct(100));
    lv_obj_set_height(ui_ArcaButt1, lv_pct(100));
    lv_obj_set_align(ui_ArcaButt1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ArcaButt1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ArcaButt1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ArcaButt1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ArcaButt1, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcaButt1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ArcaButt1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcaButt1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcaButt1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcaButt1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lantern11Button = lv_btn_create(ui_ArcaButt1);
    lv_obj_set_width(ui_Lantern11Button, 169);
    lv_obj_set_height(ui_Lantern11Button, 148);
    lv_obj_set_x(ui_Lantern11Button, -2);
    lv_obj_set_y(ui_Lantern11Button, -1);
    lv_obj_set_align(ui_Lantern11Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern11Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Lantern11Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lantern11Button, lv_color_hex(0x9CA3AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lantern11Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lantern11Button, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lantern11Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lantern11Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lantern11Label = lv_label_create(ui_Lantern11Button);
    lv_obj_set_width(ui_Lantern11Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lantern11Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Lantern11Label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Lantern11Label, "Lantaarn 11");
    lv_obj_set_style_text_color(ui_Lantern11Label, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lantern11Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network11Icon = lv_img_create(ui_Lantern11Button);
    lv_img_set_src(ui_Network11Icon, &ui_img_wifi_disabled_png);
    lv_obj_set_width(ui_Network11Icon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Network11Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Network11Icon, -10);
    lv_obj_set_y(ui_Network11Icon, 0);
    lv_obj_add_flag(ui_Network11Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Network11Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery11Icon = lv_img_create(ui_Lantern11Button);
    lv_img_set_src(ui_Battery11Icon, &ui_img_battery_disabled_png);
    lv_obj_set_width(ui_Battery11Icon, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Battery11Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Battery11Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery11Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery11Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern11Icon = lv_img_create(ui_Lantern11Button);
    lv_img_set_src(ui_Lantern11Icon, &ui_img_lantern_disabled_png);
    lv_obj_set_width(ui_Lantern11Icon, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Lantern11Icon, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_align(ui_Lantern11Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern11Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Lantern11Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Lantern11Icon, 255);

    ui_Lantern12Button = lv_btn_create(ui_ArcaButt1);
    lv_obj_set_width(ui_Lantern12Button, 169);
    lv_obj_set_height(ui_Lantern12Button, 148);
    lv_obj_set_x(ui_Lantern12Button, 3);
    lv_obj_set_y(ui_Lantern12Button, 0);
    lv_obj_set_align(ui_Lantern12Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern12Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Lantern12Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lantern12Button, lv_color_hex(0x22C55E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lantern12Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lantern12Button, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lantern12Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lantern12Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lantern12Label = lv_label_create(ui_Lantern12Button);
    lv_obj_set_width(ui_Lantern12Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lantern12Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Lantern12Label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Lantern12Label, "Lantaarn 12");
    lv_obj_set_style_text_color(ui_Lantern12Label, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lantern12Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network12Icon = lv_img_create(ui_Lantern12Button);
    lv_img_set_src(ui_Network12Icon, &ui_img_wifi_0_20_png);
    lv_obj_set_width(ui_Network12Icon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Network12Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Network12Icon, -10);
    lv_obj_set_y(ui_Network12Icon, 0);
    lv_obj_add_flag(ui_Network12Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Network12Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery12Icon = lv_img_create(ui_Lantern12Button);
    lv_img_set_src(ui_Battery12Icon, &ui_img_battery_empty_png);
    lv_obj_set_width(ui_Battery12Icon, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Battery12Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Battery12Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery12Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery12Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern12Icon = lv_img_create(ui_Lantern12Button);
    lv_img_set_src(ui_Lantern12Icon, &ui_img_lantern_off_png);
    lv_obj_set_width(ui_Lantern12Icon, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Lantern12Icon, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_align(ui_Lantern12Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern12Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Lantern12Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Lantern12Icon, 255);

    ui_Lantern13Button = lv_btn_create(ui_ArcaButt1);
    lv_obj_set_width(ui_Lantern13Button, 169);
    lv_obj_set_height(ui_Lantern13Button, 148);
    lv_obj_set_x(ui_Lantern13Button, -1);
    lv_obj_set_y(ui_Lantern13Button, 0);
    lv_obj_set_align(ui_Lantern13Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern13Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Lantern13Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lantern13Button, lv_color_hex(0xDDDDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lantern13Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lantern13Button, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lantern13Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lantern13Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lantern13Label = lv_label_create(ui_Lantern13Button);
    lv_obj_set_width(ui_Lantern13Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lantern13Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Lantern13Label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Lantern13Label, "Lantaarn 13");
    lv_obj_set_style_text_color(ui_Lantern13Label, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lantern13Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network13Icon = lv_img_create(ui_Lantern13Button);
    lv_img_set_src(ui_Network13Icon, &ui_img_wifi_20_40_png);
    lv_obj_set_width(ui_Network13Icon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Network13Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Network13Icon, -10);
    lv_obj_set_y(ui_Network13Icon, 0);
    lv_obj_add_flag(ui_Network13Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Network13Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery13Icon = lv_img_create(ui_Lantern13Button);
    lv_img_set_src(ui_Battery13Icon, &ui_img_battery_0_25_png);
    lv_obj_set_width(ui_Battery13Icon, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Battery13Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Battery13Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery13Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery13Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern13Icon = lv_img_create(ui_Lantern13Button);
    lv_img_set_src(ui_Lantern13Icon, &ui_img_lantern_on_png);
    lv_obj_set_width(ui_Lantern13Icon, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Lantern13Icon, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_align(ui_Lantern13Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern13Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Lantern13Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern14Button = lv_btn_create(ui_ArcaButt1);
    lv_obj_set_width(ui_Lantern14Button, 169);
    lv_obj_set_height(ui_Lantern14Button, 148);
    lv_obj_set_x(ui_Lantern14Button, -1);
    lv_obj_set_y(ui_Lantern14Button, 0);
    lv_obj_set_align(ui_Lantern14Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern14Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Lantern14Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lantern14Button, lv_color_hex(0x22C55E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lantern14Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lantern14Button, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lantern14Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lantern14Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lantern14Label = lv_label_create(ui_Lantern14Button);
    lv_obj_set_width(ui_Lantern14Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lantern14Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Lantern14Label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Lantern14Label, "Lantaarn 14");
    lv_obj_set_style_text_color(ui_Lantern14Label, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lantern14Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network14Icon = lv_img_create(ui_Lantern14Button);
    lv_img_set_src(ui_Network14Icon, &ui_img_wifi_40_60_png);
    lv_obj_set_width(ui_Network14Icon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Network14Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Network14Icon, -10);
    lv_obj_set_y(ui_Network14Icon, 0);
    lv_obj_add_flag(ui_Network14Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Network14Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery14Icon = lv_img_create(ui_Lantern14Button);
    lv_img_set_src(ui_Battery14Icon, &ui_img_battery_25_50_png);
    lv_obj_set_width(ui_Battery14Icon, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Battery14Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Battery14Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery14Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery14Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern14Icon = lv_img_create(ui_Lantern14Button);
    lv_img_set_src(ui_Lantern14Icon, &ui_img_lantern_on_png);
    lv_obj_set_width(ui_Lantern14Icon, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Lantern14Icon, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_align(ui_Lantern14Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern14Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Lantern14Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern15Button = lv_btn_create(ui_ArcaButt1);
    lv_obj_set_width(ui_Lantern15Button, 169);
    lv_obj_set_height(ui_Lantern15Button, 148);
    lv_obj_set_x(ui_Lantern15Button, -1);
    lv_obj_set_y(ui_Lantern15Button, 0);
    lv_obj_set_align(ui_Lantern15Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern15Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Lantern15Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lantern15Button, lv_color_hex(0x22C55E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lantern15Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lantern15Button, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lantern15Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lantern15Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lantern15Label = lv_label_create(ui_Lantern15Button);
    lv_obj_set_width(ui_Lantern15Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lantern15Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Lantern15Label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Lantern15Label, "Lantaarn 15");
    lv_obj_set_style_text_color(ui_Lantern15Label, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lantern15Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network15Icon = lv_img_create(ui_Lantern15Button);
    lv_img_set_src(ui_Network15Icon, &ui_img_wifi_60_80_png);
    lv_obj_set_width(ui_Network15Icon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Network15Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Network15Icon, -10);
    lv_obj_set_y(ui_Network15Icon, 0);
    lv_obj_add_flag(ui_Network15Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Network15Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery15Icon = lv_img_create(ui_Lantern15Button);
    lv_img_set_src(ui_Battery15Icon, &ui_img_battery_50_75_png);
    lv_obj_set_width(ui_Battery15Icon, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Battery15Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Battery15Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery15Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery15Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern15Icon = lv_img_create(ui_Lantern15Button);
    lv_img_set_src(ui_Lantern15Icon, &ui_img_lantern_off_png);
    lv_obj_set_width(ui_Lantern15Icon, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Lantern15Icon, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_align(ui_Lantern15Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern15Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Lantern15Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern16Button = lv_btn_create(ui_ArcaButt1);
    lv_obj_set_width(ui_Lantern16Button, 169);
    lv_obj_set_height(ui_Lantern16Button, 148);
    lv_obj_set_x(ui_Lantern16Button, -1);
    lv_obj_set_y(ui_Lantern16Button, 0);
    lv_obj_set_align(ui_Lantern16Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern16Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Lantern16Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lantern16Button, lv_color_hex(0x22C55E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lantern16Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lantern16Button, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lantern16Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lantern16Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lantern16Label = lv_label_create(ui_Lantern16Button);
    lv_obj_set_width(ui_Lantern16Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lantern16Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Lantern16Label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Lantern16Label, "Lantaarn 16");
    lv_obj_set_style_text_color(ui_Lantern16Label, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lantern16Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network16Icon = lv_img_create(ui_Lantern16Button);
    lv_img_set_src(ui_Network16Icon, &ui_img_wifi_80_100_png);
    lv_obj_set_width(ui_Network16Icon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Network16Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Network16Icon, -10);
    lv_obj_set_y(ui_Network16Icon, 0);
    lv_obj_add_flag(ui_Network16Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Network16Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery16Icon = lv_img_create(ui_Lantern16Button);
    lv_img_set_src(ui_Battery16Icon, &ui_img_battery_75_100_png);
    lv_obj_set_width(ui_Battery16Icon, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Battery16Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Battery16Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery16Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery16Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern16Icon = lv_img_create(ui_Lantern16Button);
    lv_img_set_src(ui_Lantern16Icon, &ui_img_lantern_on_png);
    lv_obj_set_width(ui_Lantern16Icon, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Lantern16Icon, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_Lantern16Icon, 0);
    lv_obj_set_y(ui_Lantern16Icon, -1);
    lv_obj_set_align(ui_Lantern16Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern16Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Lantern16Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern19Button = lv_btn_create(ui_ArcaButt1);
    lv_obj_set_width(ui_Lantern19Button, 169);
    lv_obj_set_height(ui_Lantern19Button, 148);
    lv_obj_set_x(ui_Lantern19Button, -2);
    lv_obj_set_y(ui_Lantern19Button, 0);
    lv_obj_set_align(ui_Lantern19Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern19Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Lantern19Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lantern19Button, lv_color_hex(0x22C55E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lantern19Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lantern19Button, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lantern19Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lantern19Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lantern19Label = lv_label_create(ui_Lantern19Button);
    lv_obj_set_width(ui_Lantern19Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lantern19Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Lantern19Label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Lantern19Label, "Lantaarn 19");
    lv_obj_set_style_text_color(ui_Lantern19Label, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lantern19Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network19Icon = lv_img_create(ui_Lantern19Button);
    lv_img_set_src(ui_Network19Icon, &ui_img_wifi_80_100_png);
    lv_obj_set_width(ui_Network19Icon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Network19Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Network19Icon, -10);
    lv_obj_set_y(ui_Network19Icon, 0);
    lv_obj_add_flag(ui_Network19Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Network19Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery19Icon = lv_img_create(ui_Lantern19Button);
    lv_img_set_src(ui_Battery19Icon, &ui_img_battery_75_100_png);
    lv_obj_set_width(ui_Battery19Icon, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Battery19Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Battery19Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery19Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery19Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern19Icon = lv_img_create(ui_Lantern19Button);
    lv_img_set_src(ui_Lantern19Icon, &ui_img_lantern_off_png);
    lv_obj_set_width(ui_Lantern19Icon, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Lantern19Icon, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_Lantern19Icon, 0);
    lv_obj_set_y(ui_Lantern19Icon, -2);
    lv_obj_set_align(ui_Lantern19Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern19Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Lantern19Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern20Button = lv_btn_create(ui_ArcaButt1);
    lv_obj_set_width(ui_Lantern20Button, 169);
    lv_obj_set_height(ui_Lantern20Button, 148);
    lv_obj_set_x(ui_Lantern20Button, -1);
    lv_obj_set_y(ui_Lantern20Button, 0);
    lv_obj_set_align(ui_Lantern20Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern20Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Lantern20Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lantern20Button, lv_color_hex(0x22C55E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lantern20Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lantern20Button, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lantern20Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lantern20Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lantern20Label = lv_label_create(ui_Lantern20Button);
    lv_obj_set_width(ui_Lantern20Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lantern20Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Lantern20Label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Lantern20Label, "Lantaarn 20");
    lv_obj_set_style_text_color(ui_Lantern20Label, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lantern20Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network20Icon = lv_img_create(ui_Lantern20Button);
    lv_img_set_src(ui_Network20Icon, &ui_img_wifi_80_100_png);
    lv_obj_set_width(ui_Network20Icon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Network20Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Network20Icon, -10);
    lv_obj_set_y(ui_Network20Icon, 0);
    lv_obj_add_flag(ui_Network20Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Network20Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery20Icon = lv_img_create(ui_Lantern20Button);
    lv_img_set_src(ui_Battery20Icon, &ui_img_battery_75_100_png);
    lv_obj_set_width(ui_Battery20Icon, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Battery20Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Battery20Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery20Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery20Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern20Icon = lv_img_create(ui_Lantern20Button);
    lv_img_set_src(ui_Lantern20Icon, &ui_img_lantern_on_png);
    lv_obj_set_width(ui_Lantern20Icon, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Lantern20Icon, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_Lantern20Icon, 0);
    lv_obj_set_y(ui_Lantern20Icon, -2);
    lv_obj_set_align(ui_Lantern20Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern20Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Lantern20Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern21Button = lv_btn_create(ui_ArcaButt1);
    lv_obj_set_width(ui_Lantern21Button, 169);
    lv_obj_set_height(ui_Lantern21Button, 148);
    lv_obj_set_x(ui_Lantern21Button, -1);
    lv_obj_set_y(ui_Lantern21Button, 0);
    lv_obj_set_align(ui_Lantern21Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern21Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Lantern21Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lantern21Button, lv_color_hex(0x22C55E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lantern21Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lantern21Button, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lantern21Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lantern21Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lantern21Label = lv_label_create(ui_Lantern21Button);
    lv_obj_set_width(ui_Lantern21Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lantern21Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Lantern21Label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Lantern21Label, "Lantaarn 21	");
    lv_obj_set_style_text_color(ui_Lantern21Label, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lantern21Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network21Icon = lv_img_create(ui_Lantern21Button);
    lv_img_set_src(ui_Network21Icon, &ui_img_wifi_80_100_png);
    lv_obj_set_width(ui_Network21Icon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Network21Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Network21Icon, -10);
    lv_obj_set_y(ui_Network21Icon, 0);
    lv_obj_add_flag(ui_Network21Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Network21Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery21Icon = lv_img_create(ui_Lantern21Button);
    lv_img_set_src(ui_Battery21Icon, &ui_img_battery_75_100_png);
    lv_obj_set_width(ui_Battery21Icon, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Battery21Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Battery21Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery21Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery21Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern21Icon = lv_img_create(ui_Lantern21Button);
    lv_img_set_src(ui_Lantern21Icon, &ui_img_lantern_off_png);
    lv_obj_set_width(ui_Lantern21Icon, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Lantern21Icon, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_Lantern21Icon, 0);
    lv_obj_set_y(ui_Lantern21Icon, -2);
    lv_obj_set_align(ui_Lantern21Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern21Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Lantern21Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern22Button = lv_btn_create(ui_ArcaButt1);
    lv_obj_set_width(ui_Lantern22Button, 169);
    lv_obj_set_height(ui_Lantern22Button, 148);
    lv_obj_set_x(ui_Lantern22Button, -1);
    lv_obj_set_y(ui_Lantern22Button, 0);
    lv_obj_set_align(ui_Lantern22Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern22Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Lantern22Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lantern22Button, lv_color_hex(0x22C55E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lantern22Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lantern22Button, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lantern22Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lantern22Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lantern22Label = lv_label_create(ui_Lantern22Button);
    lv_obj_set_width(ui_Lantern22Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lantern22Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Lantern22Label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Lantern22Label, "Lantaarn 22	");
    lv_obj_set_style_text_color(ui_Lantern22Label, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lantern22Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network22Icon = lv_img_create(ui_Lantern22Button);
    lv_img_set_src(ui_Network22Icon, &ui_img_wifi_80_100_png);
    lv_obj_set_width(ui_Network22Icon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Network22Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Network22Icon, -10);
    lv_obj_set_y(ui_Network22Icon, 0);
    lv_obj_add_flag(ui_Network22Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Network22Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery22Icon = lv_img_create(ui_Lantern22Button);
    lv_img_set_src(ui_Battery22Icon, &ui_img_battery_75_100_png);
    lv_obj_set_width(ui_Battery22Icon, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Battery22Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Battery22Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery22Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery22Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern22Icon = lv_img_create(ui_Lantern22Button);
    lv_img_set_src(ui_Lantern22Icon, &ui_img_lantern_on_png);
    lv_obj_set_width(ui_Lantern22Icon, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Lantern22Icon, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_Lantern22Icon, 0);
    lv_obj_set_y(ui_Lantern22Icon, -2);
    lv_obj_set_align(ui_Lantern22Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern22Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Lantern22Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern23Button = lv_btn_create(ui_ArcaButt1);
    lv_obj_set_width(ui_Lantern23Button, 169);
    lv_obj_set_height(ui_Lantern23Button, 148);
    lv_obj_set_x(ui_Lantern23Button, -1);
    lv_obj_set_y(ui_Lantern23Button, 0);
    lv_obj_set_align(ui_Lantern23Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern23Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Lantern23Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lantern23Button, lv_color_hex(0x22C55E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lantern23Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lantern23Button, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lantern23Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lantern23Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lantern23Label = lv_label_create(ui_Lantern23Button);
    lv_obj_set_width(ui_Lantern23Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lantern23Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Lantern23Label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Lantern23Label, "Lantaarn 23");
    lv_obj_set_style_text_color(ui_Lantern23Label, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lantern23Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network23Icon = lv_img_create(ui_Lantern23Button);
    lv_img_set_src(ui_Network23Icon, &ui_img_wifi_80_100_png);
    lv_obj_set_width(ui_Network23Icon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Network23Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Network23Icon, -10);
    lv_obj_set_y(ui_Network23Icon, 0);
    lv_obj_add_flag(ui_Network23Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Network23Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery23Icon = lv_img_create(ui_Lantern23Button);
    lv_img_set_src(ui_Battery23Icon, &ui_img_battery_75_100_png);
    lv_obj_set_width(ui_Battery23Icon, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Battery23Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Battery23Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery23Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery23Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern23Icon = lv_img_create(ui_Lantern23Button);
    lv_img_set_src(ui_Lantern23Icon, &ui_img_golem_base_png);
    lv_obj_set_width(ui_Lantern23Icon, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Lantern23Icon, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_Lantern23Icon, 0);
    lv_obj_set_y(ui_Lantern23Icon, -2);
    lv_obj_set_align(ui_Lantern23Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern23Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Lantern23Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern24Button = lv_btn_create(ui_ArcaButt1);
    lv_obj_set_width(ui_Lantern24Button, 169);
    lv_obj_set_height(ui_Lantern24Button, 148);
    lv_obj_set_x(ui_Lantern24Button, -1);
    lv_obj_set_y(ui_Lantern24Button, 0);
    lv_obj_set_align(ui_Lantern24Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern24Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Lantern24Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lantern24Button, lv_color_hex(0x22C55E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lantern24Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lantern24Button, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lantern24Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lantern24Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lantern24Label = lv_label_create(ui_Lantern24Button);
    lv_obj_set_width(ui_Lantern24Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lantern24Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Lantern24Label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Lantern24Label, "Lantaarn 24");
    lv_obj_set_style_text_color(ui_Lantern24Label, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lantern24Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network24Icon = lv_img_create(ui_Lantern24Button);
    lv_img_set_src(ui_Network24Icon, &ui_img_wifi_80_100_png);
    lv_obj_set_width(ui_Network24Icon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Network24Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Network24Icon, -10);
    lv_obj_set_y(ui_Network24Icon, 0);
    lv_obj_add_flag(ui_Network24Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Network24Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery24Icon = lv_img_create(ui_Lantern24Button);
    lv_img_set_src(ui_Battery24Icon, &ui_img_battery_75_100_png);
    lv_obj_set_width(ui_Battery24Icon, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Battery24Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Battery24Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery24Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery24Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lantern24Icon = lv_img_create(ui_Lantern24Button);
    lv_img_set_src(ui_Lantern24Icon, &ui_img_golem_on_png);
    lv_obj_set_width(ui_Lantern24Icon, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Lantern24Icon, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_Lantern24Icon, 0);
    lv_obj_set_y(ui_Lantern24Icon, -2);
    lv_obj_set_align(ui_Lantern24Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lantern24Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Lantern24Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lux2Button = lv_btn_create(ui_ArcaButt1);
    lv_obj_set_width(ui_Lux2Button, 169);
    lv_obj_set_height(ui_Lux2Button, 296);
    lv_obj_set_x(ui_Lux2Button, -1);
    lv_obj_set_y(ui_Lux2Button, 0);
    lv_obj_set_align(ui_Lux2Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lux2Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Lux2Button, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lux2Button, lv_color_hex(0xDDDDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lux2Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lux2Button, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lux2Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lux2Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lux2Label = lv_label_create(ui_Lux2Button);
    lv_obj_set_width(ui_Lux2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lux2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Lux2Label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Lux2Label, "Straler 2");
    lv_obj_set_style_text_color(ui_Lux2Label, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lux2Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network2Icon = lv_img_create(ui_Lux2Button);
    lv_img_set_src(ui_Network2Icon, &ui_img_wifi_80_100_png);
    lv_obj_set_width(ui_Network2Icon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Network2Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Network2Icon, -10);
    lv_obj_set_y(ui_Network2Icon, 0);
    lv_obj_add_flag(ui_Network2Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Network2Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery2Icon = lv_img_create(ui_Lux2Button);
    lv_img_set_src(ui_Battery2Icon, &ui_img_battery_75_100_png);
    lv_obj_set_width(ui_Battery2Icon, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Battery2Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Battery2Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery2Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery2Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lux2Icon = lv_img_create(ui_Lux2Button);
    lv_img_set_src(ui_Lux2Icon, &ui_img_gem_transparent_png);
    lv_obj_set_width(ui_Lux2Icon, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Lux2Icon, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_Lux2Icon, 1);
    lv_obj_set_y(ui_Lux2Icon, 10);
    lv_obj_set_align(ui_Lux2Icon, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Lux2Icon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Lux2Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Colorwheel2 = lv_colorwheel_create(ui_Lux2Button, true);
    lv_colorwheel_set_mode_fixed(ui_Colorwheel2, true);
    lv_obj_set_width(ui_Colorwheel2, 130);
    lv_obj_set_height(ui_Colorwheel2, 130);
    lv_obj_set_x(ui_Colorwheel2, 0);
    lv_obj_set_y(ui_Colorwheel2, 30);
    lv_obj_set_align(ui_Colorwheel2, LV_ALIGN_CENTER);

    ui_Lux3Button = lv_btn_create(ui_ArcaButt1);
    lv_obj_set_width(ui_Lux3Button, 169);
    lv_obj_set_height(ui_Lux3Button, 296);
    lv_obj_set_x(ui_Lux3Button, 1);
    lv_obj_set_y(ui_Lux3Button, 107);
    lv_obj_set_align(ui_Lux3Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lux3Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Lux3Button, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lux3Button, lv_color_hex(0x22C55E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lux3Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lux3Button, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lux3Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lux3Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lux3Label = lv_label_create(ui_Lux3Button);
    lv_obj_set_width(ui_Lux3Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lux3Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Lux3Label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Lux3Label, "Straler 3");
    lv_obj_set_style_text_color(ui_Lux3Label, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lux3Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network3Icon = lv_img_create(ui_Lux3Button);
    lv_img_set_src(ui_Network3Icon, &ui_img_wifi_80_100_png);
    lv_obj_set_width(ui_Network3Icon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Network3Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Network3Icon, -10);
    lv_obj_set_y(ui_Network3Icon, 0);
    lv_obj_add_flag(ui_Network3Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Network3Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery3Icon = lv_img_create(ui_Lux3Button);
    lv_img_set_src(ui_Battery3Icon, &ui_img_battery_75_100_png);
    lv_obj_set_width(ui_Battery3Icon, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Battery3Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Battery3Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery3Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery3Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lux3Icon = lv_img_create(ui_Lux3Button);
    lv_img_set_src(ui_Lux3Icon, &ui_img_gem_off_png);
    lv_obj_set_width(ui_Lux3Icon, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Lux3Icon, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_Lux3Icon, 1);
    lv_obj_set_y(ui_Lux3Icon, 10);
    lv_obj_set_align(ui_Lux3Icon, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Lux3Icon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Lux3Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Colorwheel3 = lv_colorwheel_create(ui_Lux3Button, true);
    lv_colorwheel_set_mode_fixed(ui_Colorwheel3, true);
    lv_obj_set_width(ui_Colorwheel3, 130);
    lv_obj_set_height(ui_Colorwheel3, 130);
    lv_obj_set_x(ui_Colorwheel3, 0);
    lv_obj_set_y(ui_Colorwheel3, 30);
    lv_obj_set_align(ui_Colorwheel3, LV_ALIGN_CENTER);

    ui_Lux4Button = lv_btn_create(ui_ArcaButt1);
    lv_obj_set_width(ui_Lux4Button, 169);
    lv_obj_set_height(ui_Lux4Button, 296);
    lv_obj_set_x(ui_Lux4Button, 0);
    lv_obj_set_y(ui_Lux4Button, -1);
    lv_obj_set_align(ui_Lux4Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lux4Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Lux4Button, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lux4Button, lv_color_hex(0x9CA3AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lux4Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lux4Button, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lux4Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lux4Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lux4Label = lv_label_create(ui_Lux4Button);
    lv_obj_set_width(ui_Lux4Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lux4Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Lux4Label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Lux4Label, "Straler 4");
    lv_obj_set_style_text_color(ui_Lux4Label, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lux4Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network4Icon = lv_img_create(ui_Lux4Button);
    lv_img_set_src(ui_Network4Icon, &ui_img_wifi_disabled_png);
    lv_obj_set_width(ui_Network4Icon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Network4Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Network4Icon, -10);
    lv_obj_set_y(ui_Network4Icon, 0);
    lv_obj_add_flag(ui_Network4Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Network4Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery4Icon = lv_img_create(ui_Lux4Button);
    lv_img_set_src(ui_Battery4Icon, &ui_img_battery_disabled_png);
    lv_obj_set_width(ui_Battery4Icon, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Battery4Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Battery4Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery4Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery4Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lux4Icon = lv_img_create(ui_Lux4Button);
    lv_img_set_src(ui_Lux4Icon, &ui_img_gem_disabled_png);
    lv_obj_set_width(ui_Lux4Icon, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Lux4Icon, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_Lux4Icon, 1);
    lv_obj_set_y(ui_Lux4Icon, 10);
    lv_obj_set_align(ui_Lux4Icon, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Lux4Icon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Lux4Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Colorwheel4 = lv_colorwheel_create(ui_Lux4Button, true);
    lv_colorwheel_set_mode_fixed(ui_Colorwheel4, true);
    lv_obj_set_width(ui_Colorwheel4, 130);
    lv_obj_set_height(ui_Colorwheel4, 130);
    lv_obj_set_x(ui_Colorwheel4, 0);
    lv_obj_set_y(ui_Colorwheel4, 30);
    lv_obj_set_align(ui_Colorwheel4, LV_ALIGN_CENTER);

    ui_EasterButton = lv_btn_create(ui_ArcaButt1);
    lv_obj_set_width(ui_EasterButton, 169);
    lv_obj_set_height(ui_EasterButton, 296);
    lv_obj_set_x(ui_EasterButton, 0);
    lv_obj_set_y(ui_EasterButton, -1);
    lv_obj_set_align(ui_EasterButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EasterButton, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_EasterButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_EasterButton, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EasterButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_EasterButton, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EasterButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_EasterButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GemGlyph71Button = lv_btn_create(ui_ArcaButt1);
    lv_obj_set_width(ui_GemGlyph71Button, 169);
    lv_obj_set_height(ui_GemGlyph71Button, 296);
    lv_obj_set_x(ui_GemGlyph71Button, 0);
    lv_obj_set_y(ui_GemGlyph71Button, -1);
    lv_obj_set_align(ui_GemGlyph71Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GemGlyph71Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GemGlyph71Button, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GemGlyph71Button, lv_color_hex(0x5CABB0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GemGlyph71Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GemGlyph71Button, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GemGlyph71Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GemGlyph71Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GemGlyph71Label = lv_label_create(ui_GemGlyph71Button);
    lv_obj_set_width(ui_GemGlyph71Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GemGlyph71Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GemGlyph71Label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_GemGlyph71Label, "GemGlyph 71");
    lv_obj_set_style_text_color(ui_GemGlyph71Label, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GemGlyph71Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GemGlyph71Icon = lv_img_create(ui_GemGlyph71Button);
    lv_img_set_src(ui_GemGlyph71Icon, &ui_img_golem_off_png);
    lv_obj_set_width(ui_GemGlyph71Icon, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_GemGlyph71Icon, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_GemGlyph71Icon, 1);
    lv_obj_set_y(ui_GemGlyph71Icon, 60);
    lv_obj_set_align(ui_GemGlyph71Icon, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_GemGlyph71Icon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_GemGlyph71Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_GemGlyph71Icon, 255);

    ui_GemGlyph71InButton = lv_btn_create(ui_GemGlyph71Button);
    lv_obj_set_width(ui_GemGlyph71InButton, 54);
    lv_obj_set_height(ui_GemGlyph71InButton, 50);
    lv_obj_set_x(ui_GemGlyph71InButton, -10);
    lv_obj_set_y(ui_GemGlyph71InButton, 0);
    lv_obj_add_flag(ui_GemGlyph71InButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GemGlyph71InButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GemGlyph71InButton, lv_color_hex(0x009E3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GemGlyph71InButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GemGlyph71InButtonLabel = lv_label_create(ui_GemGlyph71InButton);
    lv_obj_set_width(ui_GemGlyph71InButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GemGlyph71InButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GemGlyph71InButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GemGlyph71InButtonLabel, "IN");
    lv_obj_set_style_text_color(ui_GemGlyph71InButtonLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GemGlyph71InButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GemGlyph71InButtonLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GemGlyph71OutButton = lv_btn_create(ui_GemGlyph71Button);
    lv_obj_set_width(ui_GemGlyph71OutButton, 54);
    lv_obj_set_height(ui_GemGlyph71OutButton, 50);
    lv_obj_set_x(ui_GemGlyph71OutButton, 10);
    lv_obj_set_y(ui_GemGlyph71OutButton, 0);
    lv_obj_set_align(ui_GemGlyph71OutButton, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_GemGlyph71OutButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GemGlyph71OutButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GemGlyph71OutButton, lv_color_hex(0x009E3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GemGlyph71OutButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GemGlyph71OutButtonLabel = lv_label_create(ui_GemGlyph71OutButton);
    lv_obj_set_width(ui_GemGlyph71OutButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GemGlyph71OutButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GemGlyph71OutButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GemGlyph71OutButtonLabel, "UIT");
    lv_obj_set_style_text_color(ui_GemGlyph71OutButtonLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GemGlyph71OutButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GemGlyph71OutButtonLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EggButton = lv_btn_create(ui_ArcaButt1);
    lv_obj_set_width(ui_EggButton, 169);
    lv_obj_set_height(ui_EggButton, 296);
    lv_obj_set_x(ui_EggButton, 0);
    lv_obj_set_y(ui_EggButton, -1);
    lv_obj_set_align(ui_EggButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EggButton, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_EggButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_EggButton, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EggButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_EggButton, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EggButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_EggButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EasterEggResult = lv_label_create(ui_EggButton);
    lv_obj_set_width(ui_EasterEggResult, 150);
    lv_obj_set_height(ui_EasterEggResult, 250);
    lv_obj_set_align(ui_EasterEggResult, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EasterEggResult, "");
    lv_obj_set_style_bg_color(ui_EasterEggResult, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EasterEggResult, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Lux2Icon, ui_event_Lux2Icon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Colorwheel2, ui_event_Colorwheel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Lux3Icon, ui_event_Lux3Icon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Colorwheel3, ui_event_Colorwheel3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Lux4Icon, ui_event_Lux4Icon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Colorwheel4, ui_event_Colorwheel4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_EasterButton, ui_event_EasterButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GemGlyph71InButton, ui_event_GemGlyph71InButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GemGlyph71OutButton, ui_event_GemGlyph71OutButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_EggButton, ui_event_EggButton, LV_EVENT_ALL, NULL);
    uic_Screen2 = ui_Screen2;
    uic_Lantern11Button = ui_Lantern11Button;
    uic_Lantern11Label = ui_Lantern11Label;
    uic_Network11Icon = ui_Network11Icon;
    uic_Battery11Icon = ui_Battery11Icon;
    uic_Lantern11Icon = ui_Lantern11Icon;
    uic_Lantern12Button = ui_Lantern12Button;
    uic_Lantern12Label = ui_Lantern12Label;
    uic_Network12Icon = ui_Network12Icon;
    uic_Battery12Icon = ui_Battery12Icon;
    uic_Lantern12Icon = ui_Lantern12Icon;
    uic_Lantern13Button = ui_Lantern13Button;
    uic_Lantern13Label = ui_Lantern13Label;
    uic_Network13Icon = ui_Network13Icon;
    uic_Battery13Icon = ui_Battery13Icon;
    uic_Lantern13Icon = ui_Lantern13Icon;
    uic_Lantern14Button = ui_Lantern14Button;
    uic_Lantern14Label = ui_Lantern14Label;
    uic_Network14Icon = ui_Network14Icon;
    uic_Battery14Icon = ui_Battery14Icon;
    uic_Lantern14Icon = ui_Lantern14Icon;
    uic_Lantern15Button = ui_Lantern15Button;
    uic_Lantern15Label = ui_Lantern15Label;
    uic_Network15Icon = ui_Network15Icon;
    uic_Battery15Icon = ui_Battery15Icon;
    uic_Lantern15Icon = ui_Lantern15Icon;
    uic_Lantern16Button = ui_Lantern16Button;
    uic_Lantern16Label = ui_Lantern16Label;
    uic_Network16Icon = ui_Network16Icon;
    uic_Battery16Icon = ui_Battery16Icon;
    uic_Lantern16Icon = ui_Lantern16Icon;
    uic_Lantern19Button = ui_Lantern19Button;
    uic_Lantern19Label = ui_Lantern19Label;
    uic_Network19Icon = ui_Network19Icon;
    uic_Battery19Icon = ui_Battery19Icon;
    uic_Lantern19Icon = ui_Lantern19Icon;
    uic_Lantern20Button = ui_Lantern20Button;
    uic_Lantern20Label = ui_Lantern20Label;
    uic_Network20Icon = ui_Network20Icon;
    uic_Battery20Icon = ui_Battery20Icon;
    uic_Lantern20Icon = ui_Lantern20Icon;
    uic_Lantern21Button = ui_Lantern21Button;
    uic_Lantern21Label = ui_Lantern21Label;
    uic_Network21Icon = ui_Network21Icon;
    uic_Battery21Icon = ui_Battery21Icon;
    uic_Lantern21Icon = ui_Lantern21Icon;
    uic_Lantern22Button = ui_Lantern22Button;
    uic_Lantern22Label = ui_Lantern22Label;
    uic_Network22Icon = ui_Network22Icon;
    uic_Battery22Icon = ui_Battery22Icon;
    uic_Lantern22Icon = ui_Lantern22Icon;
    uic_Lantern23Button = ui_Lantern23Button;
    uic_Lantern23Label = ui_Lantern23Label;
    uic_Network23Icon = ui_Network23Icon;
    uic_Battery23Icon = ui_Battery23Icon;
    uic_Lantern23Icon = ui_Lantern23Icon;
    uic_Lantern24Button = ui_Lantern24Button;
    uic_Lantern24Label = ui_Lantern24Label;
    uic_Network24Icon = ui_Network24Icon;
    uic_Battery24Icon = ui_Battery24Icon;
    uic_Lantern24Icon = ui_Lantern24Icon;
    uic_Lux2Button = ui_Lux2Button;
    uic_Lux2Label = ui_Lux2Label;
    uic_Network2Icon = ui_Network2Icon;
    uic_Battery2Icon = ui_Battery2Icon;
    uic_Lux2Icon = ui_Lux2Icon;
    uic_Colorwheel2 = ui_Colorwheel2;
    uic_Lux3Button = ui_Lux3Button;
    uic_Lux3Label = ui_Lux3Label;
    uic_Network3Icon = ui_Network3Icon;
    uic_Battery3Icon = ui_Battery3Icon;
    uic_Lux3Icon = ui_Lux3Icon;
    uic_Colorwheel3 = ui_Colorwheel3;
    uic_Lux4Button = ui_Lux4Button;
    uic_Lux4Label = ui_Lux4Label;
    uic_Network4Icon = ui_Network4Icon;
    uic_Battery4Icon = ui_Battery4Icon;
    uic_Lux4Icon = ui_Lux4Icon;
    uic_Colorwheel4 = ui_Colorwheel4;
    uic_EasterButton = ui_EasterButton;
    uic_GemGlyph71Button = ui_GemGlyph71Button;
    uic_GemGlyph71Label = ui_GemGlyph71Label;
    uic_GemGlyph71Icon = ui_GemGlyph71Icon;
    uic_GemGlyph71OutButton = ui_GemGlyph71OutButton;
    uic_GemGlyph71OutButtonLabel = ui_GemGlyph71OutButtonLabel;
    uic_EasterEggResult = ui_EasterEggResult;

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    uic_Screen2 = NULL;
    ui_Screen2 = NULL;
    ui_ArcaButt1 = NULL;
    uic_Lantern11Button = NULL;
    ui_Lantern11Button = NULL;
    uic_Lantern11Label = NULL;
    ui_Lantern11Label = NULL;
    uic_Network11Icon = NULL;
    ui_Network11Icon = NULL;
    uic_Battery11Icon = NULL;
    ui_Battery11Icon = NULL;
    uic_Lantern11Icon = NULL;
    ui_Lantern11Icon = NULL;
    uic_Lantern12Button = NULL;
    ui_Lantern12Button = NULL;
    uic_Lantern12Label = NULL;
    ui_Lantern12Label = NULL;
    uic_Network12Icon = NULL;
    ui_Network12Icon = NULL;
    uic_Battery12Icon = NULL;
    ui_Battery12Icon = NULL;
    uic_Lantern12Icon = NULL;
    ui_Lantern12Icon = NULL;
    uic_Lantern13Button = NULL;
    ui_Lantern13Button = NULL;
    uic_Lantern13Label = NULL;
    ui_Lantern13Label = NULL;
    uic_Network13Icon = NULL;
    ui_Network13Icon = NULL;
    uic_Battery13Icon = NULL;
    ui_Battery13Icon = NULL;
    uic_Lantern13Icon = NULL;
    ui_Lantern13Icon = NULL;
    uic_Lantern14Button = NULL;
    ui_Lantern14Button = NULL;
    uic_Lantern14Label = NULL;
    ui_Lantern14Label = NULL;
    uic_Network14Icon = NULL;
    ui_Network14Icon = NULL;
    uic_Battery14Icon = NULL;
    ui_Battery14Icon = NULL;
    uic_Lantern14Icon = NULL;
    ui_Lantern14Icon = NULL;
    uic_Lantern15Button = NULL;
    ui_Lantern15Button = NULL;
    uic_Lantern15Label = NULL;
    ui_Lantern15Label = NULL;
    uic_Network15Icon = NULL;
    ui_Network15Icon = NULL;
    uic_Battery15Icon = NULL;
    ui_Battery15Icon = NULL;
    uic_Lantern15Icon = NULL;
    ui_Lantern15Icon = NULL;
    uic_Lantern16Button = NULL;
    ui_Lantern16Button = NULL;
    uic_Lantern16Label = NULL;
    ui_Lantern16Label = NULL;
    uic_Network16Icon = NULL;
    ui_Network16Icon = NULL;
    uic_Battery16Icon = NULL;
    ui_Battery16Icon = NULL;
    uic_Lantern16Icon = NULL;
    ui_Lantern16Icon = NULL;
    uic_Lantern19Button = NULL;
    ui_Lantern19Button = NULL;
    uic_Lantern19Label = NULL;
    ui_Lantern19Label = NULL;
    uic_Network19Icon = NULL;
    ui_Network19Icon = NULL;
    uic_Battery19Icon = NULL;
    ui_Battery19Icon = NULL;
    uic_Lantern19Icon = NULL;
    ui_Lantern19Icon = NULL;
    uic_Lantern20Button = NULL;
    ui_Lantern20Button = NULL;
    uic_Lantern20Label = NULL;
    ui_Lantern20Label = NULL;
    uic_Network20Icon = NULL;
    ui_Network20Icon = NULL;
    uic_Battery20Icon = NULL;
    ui_Battery20Icon = NULL;
    uic_Lantern20Icon = NULL;
    ui_Lantern20Icon = NULL;
    uic_Lantern21Button = NULL;
    ui_Lantern21Button = NULL;
    uic_Lantern21Label = NULL;
    ui_Lantern21Label = NULL;
    uic_Network21Icon = NULL;
    ui_Network21Icon = NULL;
    uic_Battery21Icon = NULL;
    ui_Battery21Icon = NULL;
    uic_Lantern21Icon = NULL;
    ui_Lantern21Icon = NULL;
    uic_Lantern22Button = NULL;
    ui_Lantern22Button = NULL;
    uic_Lantern22Label = NULL;
    ui_Lantern22Label = NULL;
    uic_Network22Icon = NULL;
    ui_Network22Icon = NULL;
    uic_Battery22Icon = NULL;
    ui_Battery22Icon = NULL;
    uic_Lantern22Icon = NULL;
    ui_Lantern22Icon = NULL;
    uic_Lantern23Button = NULL;
    ui_Lantern23Button = NULL;
    uic_Lantern23Label = NULL;
    ui_Lantern23Label = NULL;
    uic_Network23Icon = NULL;
    ui_Network23Icon = NULL;
    uic_Battery23Icon = NULL;
    ui_Battery23Icon = NULL;
    uic_Lantern23Icon = NULL;
    ui_Lantern23Icon = NULL;
    uic_Lantern24Button = NULL;
    ui_Lantern24Button = NULL;
    uic_Lantern24Label = NULL;
    ui_Lantern24Label = NULL;
    uic_Network24Icon = NULL;
    ui_Network24Icon = NULL;
    uic_Battery24Icon = NULL;
    ui_Battery24Icon = NULL;
    uic_Lantern24Icon = NULL;
    ui_Lantern24Icon = NULL;
    uic_Lux2Button = NULL;
    ui_Lux2Button = NULL;
    uic_Lux2Label = NULL;
    ui_Lux2Label = NULL;
    uic_Network2Icon = NULL;
    ui_Network2Icon = NULL;
    uic_Battery2Icon = NULL;
    ui_Battery2Icon = NULL;
    uic_Lux2Icon = NULL;
    ui_Lux2Icon = NULL;
    uic_Colorwheel2 = NULL;
    ui_Colorwheel2 = NULL;
    uic_Lux3Button = NULL;
    ui_Lux3Button = NULL;
    uic_Lux3Label = NULL;
    ui_Lux3Label = NULL;
    uic_Network3Icon = NULL;
    ui_Network3Icon = NULL;
    uic_Battery3Icon = NULL;
    ui_Battery3Icon = NULL;
    uic_Lux3Icon = NULL;
    ui_Lux3Icon = NULL;
    uic_Colorwheel3 = NULL;
    ui_Colorwheel3 = NULL;
    uic_Lux4Button = NULL;
    ui_Lux4Button = NULL;
    uic_Lux4Label = NULL;
    ui_Lux4Label = NULL;
    uic_Network4Icon = NULL;
    ui_Network4Icon = NULL;
    uic_Battery4Icon = NULL;
    ui_Battery4Icon = NULL;
    uic_Lux4Icon = NULL;
    ui_Lux4Icon = NULL;
    uic_Colorwheel4 = NULL;
    ui_Colorwheel4 = NULL;
    uic_EasterButton = NULL;
    ui_EasterButton = NULL;
    uic_GemGlyph71Button = NULL;
    ui_GemGlyph71Button = NULL;
    uic_GemGlyph71Label = NULL;
    ui_GemGlyph71Label = NULL;
    uic_GemGlyph71Icon = NULL;
    ui_GemGlyph71Icon = NULL;
    ui_GemGlyph71InButton = NULL;
    ui_GemGlyph71InButtonLabel = NULL;
    uic_GemGlyph71OutButton = NULL;
    ui_GemGlyph71OutButton = NULL;
    uic_GemGlyph71OutButtonLabel = NULL;
    ui_GemGlyph71OutButtonLabel = NULL;
    ui_EggButton = NULL;
    uic_EasterEggResult = NULL;
    ui_EasterEggResult = NULL;

}
