// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ArcaFace

#include "../ui.h"

lv_obj_t * uic_Slider2;
lv_obj_t * uic_Colorwheel2;
lv_obj_t * uic_Battery2Icon;
lv_obj_t * uic_Network2Icon;
lv_obj_t * uic_Lux2Label;
lv_obj_t * uic_Lux2Button;
lv_obj_t * uic_Slider1;
lv_obj_t * uic_Colorwheel1;
lv_obj_t * uic_Battery1Icon;
lv_obj_t * uic_Network1Icon;
lv_obj_t * uic_Lux1Label;
lv_obj_t * uic_Lux1Button;
lv_obj_t * uic_Screen1;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_Lux1Button = NULL;
lv_obj_t * ui_Lux1Label = NULL;
lv_obj_t * ui_Network1Icon = NULL;
lv_obj_t * ui_Battery1Icon = NULL;
lv_obj_t * ui_Colorwheel1 = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_Lux2Button = NULL;
lv_obj_t * ui_Lux2Label = NULL;
lv_obj_t * ui_Network2Icon = NULL;
lv_obj_t * ui_Battery2Icon = NULL;
lv_obj_t * ui_Colorwheel2 = NULL;
lv_obj_t * ui_Slider2 = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_Colorwheel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        setColorLux1(e);
    }
}

void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        setBrightnessLux1(e);
    }
}

void ui_event_Colorwheel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        setColorLux2(e);
    }
}

void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        setBrightnessLux2(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, lv_pct(100));
    lv_obj_set_height(ui_Container1, lv_pct(100));
    lv_obj_set_x(ui_Container1, 3);
    lv_obj_set_y(ui_Container1, -1);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, lv_pct(20));
    lv_obj_set_height(ui_Container4, lv_pct(100));
    lv_obj_set_x(ui_Container4, 3);
    lv_obj_set_y(ui_Container4, 0);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_Container4);
    lv_obj_set_width(ui_Button1, lv_pct(98));
    lv_obj_set_height(ui_Button1, lv_pct(20));
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFF7474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button1, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Lantaarns");

    ui_Button2 = lv_btn_create(ui_Container4);
    lv_obj_set_width(ui_Button2, lv_pct(98));
    lv_obj_set_height(ui_Button2, lv_pct(20));
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFF7474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button2, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Console");

    ui_Container5 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, lv_pct(80));
    lv_obj_set_height(ui_Container5, lv_pct(100));
    lv_obj_set_x(ui_Container5, 13);
    lv_obj_set_y(ui_Container5, 118);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Lux1Button = lv_btn_create(ui_Container5);
    lv_obj_set_height(ui_Lux1Button, 297);
    lv_obj_set_width(ui_Lux1Button, lv_pct(33));
    lv_obj_set_align(ui_Lux1Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lux1Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Lux1Button, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lux1Button, lv_color_hex(0x8F8376), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lux1Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lux1Button, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lux1Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lux1Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lux1Label = lv_label_create(ui_Lux1Button);
    lv_obj_set_width(ui_Lux1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lux1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Lux1Label, -13);
    lv_obj_set_y(ui_Lux1Label, -251);
    lv_obj_set_align(ui_Lux1Label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Lux1Label, "Straler 1");
    lv_obj_set_style_text_color(ui_Lux1Label, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lux1Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network1Icon = lv_img_create(ui_Lux1Button);
    lv_img_set_src(ui_Network1Icon, &ui_img_wifi_disabled_png);
    lv_obj_set_width(ui_Network1Icon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Network1Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Network1Icon, -190);
    lv_obj_set_y(ui_Network1Icon, 0);
    lv_obj_set_align(ui_Network1Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Network1Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Network1Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery1Icon = lv_img_create(ui_Lux1Button);
    lv_img_set_src(ui_Battery1Icon, &ui_img_battery_disabled_png);
    lv_obj_set_width(ui_Battery1Icon, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Battery1Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Battery1Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery1Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery1Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Colorwheel1 = lv_colorwheel_create(ui_Lux1Button, true);
    lv_colorwheel_set_mode_fixed(ui_Colorwheel1, true);
    lv_obj_set_width(ui_Colorwheel1, 180);
    lv_obj_set_height(ui_Colorwheel1, 180);
    lv_obj_set_x(ui_Colorwheel1, 15);
    lv_obj_set_y(ui_Colorwheel1, -20);
    lv_obj_set_align(ui_Colorwheel1, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_blend_mode(ui_Colorwheel1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Colorwheel1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_Lux1Button);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_Slider1, 20);
    lv_obj_set_width(ui_Slider1, lv_pct(96));
    lv_obj_set_x(ui_Slider1, 0);
    lv_obj_set_y(ui_Slider1, 120);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_radius(ui_Slider1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider1, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Slider1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slider1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Slider1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Slider1, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slider1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Slider1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Slider1, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Slider1, 4, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Lux2Button = lv_btn_create(ui_Container5);
    lv_obj_set_height(ui_Lux2Button, 297);
    lv_obj_set_width(ui_Lux2Button, lv_pct(33));
    lv_obj_set_align(ui_Lux2Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lux2Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Lux2Button, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lux2Button, lv_color_hex(0x9CA3AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lux2Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lux2Button, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lux2Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lux2Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lux2Label = lv_label_create(ui_Lux2Button);
    lv_obj_set_width(ui_Lux2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lux2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Lux2Label, -13);
    lv_obj_set_y(ui_Lux2Label, -252);
    lv_obj_set_align(ui_Lux2Label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Lux2Label, "Straler 2");
    lv_obj_set_style_text_color(ui_Lux2Label, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lux2Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network2Icon = lv_img_create(ui_Lux2Button);
    lv_img_set_src(ui_Network2Icon, &ui_img_wifi_disabled_png);
    lv_obj_set_width(ui_Network2Icon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Network2Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Network2Icon, -200);
    lv_obj_set_y(ui_Network2Icon, 0);
    lv_obj_set_align(ui_Network2Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Network2Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Network2Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery2Icon = lv_img_create(ui_Lux2Button);
    lv_img_set_src(ui_Battery2Icon, &ui_img_battery_disabled_png);
    lv_obj_set_width(ui_Battery2Icon, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Battery2Icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Battery2Icon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery2Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery2Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Colorwheel2 = lv_colorwheel_create(ui_Lux2Button, true);
    lv_colorwheel_set_mode_fixed(ui_Colorwheel2, true);
    lv_obj_set_width(ui_Colorwheel2, 180);
    lv_obj_set_height(ui_Colorwheel2, 180);
    lv_obj_set_x(ui_Colorwheel2, 15);
    lv_obj_set_y(ui_Colorwheel2, -20);
    lv_obj_set_align(ui_Colorwheel2, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_blend_mode(ui_Colorwheel2, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Colorwheel2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_Lux2Button);
    lv_slider_set_value(ui_Slider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_Slider2, 20);
    lv_obj_set_width(ui_Slider2, lv_pct(96));
    lv_obj_set_x(ui_Slider2, 0);
    lv_obj_set_y(ui_Slider2, 120);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_radius(ui_Slider2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider2, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Slider2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Slider2, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Slider2, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slider2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Slider2, 4, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Colorwheel1, ui_event_Colorwheel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Colorwheel2, ui_event_Colorwheel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);
    uic_Screen1 = ui_Screen1;
    uic_Lux1Button = ui_Lux1Button;
    uic_Lux1Label = ui_Lux1Label;
    uic_Network1Icon = ui_Network1Icon;
    uic_Battery1Icon = ui_Battery1Icon;
    uic_Colorwheel1 = ui_Colorwheel1;
    uic_Slider1 = ui_Slider1;
    uic_Lux2Button = ui_Lux2Button;
    uic_Lux2Label = ui_Lux2Label;
    uic_Network2Icon = ui_Network2Icon;
    uic_Battery2Icon = ui_Battery2Icon;
    uic_Colorwheel2 = ui_Colorwheel2;
    uic_Slider2 = ui_Slider2;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    uic_Screen1 = NULL;
    ui_Screen1 = NULL;
    ui_Container1 = NULL;
    ui_Container4 = NULL;
    ui_Button1 = NULL;
    ui_Label1 = NULL;
    ui_Button2 = NULL;
    ui_Label2 = NULL;
    ui_Container5 = NULL;
    uic_Lux1Button = NULL;
    ui_Lux1Button = NULL;
    uic_Lux1Label = NULL;
    ui_Lux1Label = NULL;
    uic_Network1Icon = NULL;
    ui_Network1Icon = NULL;
    uic_Battery1Icon = NULL;
    ui_Battery1Icon = NULL;
    uic_Colorwheel1 = NULL;
    ui_Colorwheel1 = NULL;
    uic_Slider1 = NULL;
    ui_Slider1 = NULL;
    uic_Lux2Button = NULL;
    ui_Lux2Button = NULL;
    uic_Lux2Label = NULL;
    ui_Lux2Label = NULL;
    uic_Network2Icon = NULL;
    ui_Network2Icon = NULL;
    uic_Battery2Icon = NULL;
    ui_Battery2Icon = NULL;
    uic_Colorwheel2 = NULL;
    ui_Colorwheel2 = NULL;
    uic_Slider2 = NULL;
    ui_Slider2 = NULL;

}
