// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ArcaFace

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_ArcaButt1;
extern lv_obj_t * ui_Lantern11Button;
extern lv_obj_t * ui_Lantern11Label;
extern lv_obj_t * ui_Network11Icon;
extern lv_obj_t * ui_Battery11Icon;
extern lv_obj_t * ui_Lantern11Icon;
extern lv_obj_t * ui_Lantern12Button;
extern lv_obj_t * ui_Lantern12Label;
extern lv_obj_t * ui_Network12Icon;
extern lv_obj_t * ui_Battery12Icon;
extern lv_obj_t * ui_Lantern12Icon;
extern lv_obj_t * ui_Lantern13Button;
extern lv_obj_t * ui_Lantern13Label;
extern lv_obj_t * ui_Network13Icon;
extern lv_obj_t * ui_Battery13Icon;
extern lv_obj_t * ui_Lantern13Icon;
extern lv_obj_t * ui_Lantern14Button;
extern lv_obj_t * ui_Lantern14Label;
extern lv_obj_t * ui_Network14Icon;
extern lv_obj_t * ui_Battery14Icon;
extern lv_obj_t * ui_Lantern14Icon;
extern lv_obj_t * ui_Lantern15Button;
extern lv_obj_t * ui_Lantern15Label;
extern lv_obj_t * ui_Network15Icon;
extern lv_obj_t * ui_Battery15Icon;
extern lv_obj_t * ui_Lantern15Icon;
extern lv_obj_t * ui_Lantern16Button;
extern lv_obj_t * ui_Lantern16Label;
extern lv_obj_t * ui_Network16Icon;
extern lv_obj_t * ui_Battery16Icon;
extern lv_obj_t * ui_Lantern16Icon;
extern lv_obj_t * ui_Lantern19Button;
extern lv_obj_t * ui_Lantern19Label;
extern lv_obj_t * ui_Network19Icon;
extern lv_obj_t * ui_Battery19Icon;
extern lv_obj_t * ui_Lantern19Icon;
extern lv_obj_t * ui_Lantern20Button;
extern lv_obj_t * ui_Lantern20Label;
extern lv_obj_t * ui_Network20Icon;
extern lv_obj_t * ui_Battery20Icon;
extern lv_obj_t * ui_Lantern20Icon;
extern lv_obj_t * ui_Lantern21Button;
extern lv_obj_t * ui_Lantern21Label;
extern lv_obj_t * ui_Network21Icon;
extern lv_obj_t * ui_Battery21Icon;
extern lv_obj_t * ui_Lantern21Icon;
extern lv_obj_t * ui_Lantern22Button;
extern lv_obj_t * ui_Lantern22Label;
extern lv_obj_t * ui_Network22Icon;
extern lv_obj_t * ui_Battery22Icon;
extern lv_obj_t * ui_Lantern22Icon;
extern lv_obj_t * ui_Lantern23Button;
extern lv_obj_t * ui_Lantern23Label;
extern lv_obj_t * ui_Network23Icon;
extern lv_obj_t * ui_Battery23Icon;
extern lv_obj_t * ui_Lantern23Icon;
extern lv_obj_t * ui_Lantern24Button;
extern lv_obj_t * ui_Lantern24Label;
extern lv_obj_t * ui_Network24Icon;
extern lv_obj_t * ui_Battery24Icon;
extern lv_obj_t * ui_Lantern24Icon;
extern lv_obj_t * ui_Lux2Button;
extern lv_obj_t * ui_Lux2Label;
extern lv_obj_t * ui_Network2Icon;
extern lv_obj_t * ui_Battery2Icon;
extern void ui_event_Lux2Icon(lv_event_t * e);
extern lv_obj_t * ui_Lux2Icon;
extern void ui_event_Colorwheel2(lv_event_t * e);
extern lv_obj_t * ui_Colorwheel2;
extern lv_obj_t * ui_Lux3Button;
extern lv_obj_t * ui_Lux3Label;
extern lv_obj_t * ui_Network3Icon;
extern lv_obj_t * ui_Battery3Icon;
extern void ui_event_Lux3Icon(lv_event_t * e);
extern lv_obj_t * ui_Lux3Icon;
extern void ui_event_Colorwheel3(lv_event_t * e);
extern lv_obj_t * ui_Colorwheel3;
extern lv_obj_t * ui_Lux4Button;
extern lv_obj_t * ui_Lux4Label;
extern lv_obj_t * ui_Network4Icon;
extern lv_obj_t * ui_Battery4Icon;
extern void ui_event_Lux4Icon(lv_event_t * e);
extern lv_obj_t * ui_Lux4Icon;
extern void ui_event_Colorwheel4(lv_event_t * e);
extern lv_obj_t * ui_Colorwheel4;
extern void ui_event_EasterButton(lv_event_t * e);
extern lv_obj_t * ui_EasterButton;
extern lv_obj_t * ui_GemGlyph71Button;
extern lv_obj_t * ui_GemGlyph71Label;
extern lv_obj_t * ui_GemGlyph71Icon;
extern void ui_event_GemGlyph71InButton(lv_event_t * e);
extern lv_obj_t * ui_GemGlyph71InButton;
extern lv_obj_t * ui_GemGlyph71InButtonLabel;
extern void ui_event_GemGlyph71OutButton(lv_event_t * e);
extern lv_obj_t * ui_GemGlyph71OutButton;
extern lv_obj_t * ui_GemGlyph71OutButtonLabel;
extern void ui_event_EggButton(lv_event_t * e);
extern lv_obj_t * ui_EggButton;
extern lv_obj_t * ui_EasterEggResult;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen2;
extern lv_obj_t * uic_Lantern11Button;
extern lv_obj_t * uic_Lantern11Label;
extern lv_obj_t * uic_Network11Icon;
extern lv_obj_t * uic_Battery11Icon;
extern lv_obj_t * uic_Lantern11Icon;
extern lv_obj_t * uic_Lantern12Button;
extern lv_obj_t * uic_Lantern12Label;
extern lv_obj_t * uic_Network12Icon;
extern lv_obj_t * uic_Battery12Icon;
extern lv_obj_t * uic_Lantern12Icon;
extern lv_obj_t * uic_Lantern13Button;
extern lv_obj_t * uic_Lantern13Label;
extern lv_obj_t * uic_Network13Icon;
extern lv_obj_t * uic_Battery13Icon;
extern lv_obj_t * uic_Lantern13Icon;
extern lv_obj_t * uic_Lantern14Button;
extern lv_obj_t * uic_Lantern14Label;
extern lv_obj_t * uic_Network14Icon;
extern lv_obj_t * uic_Battery14Icon;
extern lv_obj_t * uic_Lantern14Icon;
extern lv_obj_t * uic_Lantern15Button;
extern lv_obj_t * uic_Lantern15Label;
extern lv_obj_t * uic_Network15Icon;
extern lv_obj_t * uic_Battery15Icon;
extern lv_obj_t * uic_Lantern15Icon;
extern lv_obj_t * uic_Lantern16Button;
extern lv_obj_t * uic_Lantern16Label;
extern lv_obj_t * uic_Network16Icon;
extern lv_obj_t * uic_Battery16Icon;
extern lv_obj_t * uic_Lantern16Icon;
extern lv_obj_t * uic_Lantern19Button;
extern lv_obj_t * uic_Lantern19Label;
extern lv_obj_t * uic_Network19Icon;
extern lv_obj_t * uic_Battery19Icon;
extern lv_obj_t * uic_Lantern19Icon;
extern lv_obj_t * uic_Lantern20Button;
extern lv_obj_t * uic_Lantern20Label;
extern lv_obj_t * uic_Network20Icon;
extern lv_obj_t * uic_Battery20Icon;
extern lv_obj_t * uic_Lantern20Icon;
extern lv_obj_t * uic_Lantern21Button;
extern lv_obj_t * uic_Lantern21Label;
extern lv_obj_t * uic_Network21Icon;
extern lv_obj_t * uic_Battery21Icon;
extern lv_obj_t * uic_Lantern21Icon;
extern lv_obj_t * uic_Lantern22Button;
extern lv_obj_t * uic_Lantern22Label;
extern lv_obj_t * uic_Network22Icon;
extern lv_obj_t * uic_Battery22Icon;
extern lv_obj_t * uic_Lantern22Icon;
extern lv_obj_t * uic_Lantern23Button;
extern lv_obj_t * uic_Lantern23Label;
extern lv_obj_t * uic_Network23Icon;
extern lv_obj_t * uic_Battery23Icon;
extern lv_obj_t * uic_Lantern23Icon;
extern lv_obj_t * uic_Lantern24Button;
extern lv_obj_t * uic_Lantern24Label;
extern lv_obj_t * uic_Network24Icon;
extern lv_obj_t * uic_Battery24Icon;
extern lv_obj_t * uic_Lantern24Icon;
extern lv_obj_t * uic_Lux2Button;
extern lv_obj_t * uic_Lux2Label;
extern lv_obj_t * uic_Network2Icon;
extern lv_obj_t * uic_Battery2Icon;
extern lv_obj_t * uic_Lux2Icon;
extern lv_obj_t * uic_Colorwheel2;
extern lv_obj_t * uic_Lux3Button;
extern lv_obj_t * uic_Lux3Label;
extern lv_obj_t * uic_Network3Icon;
extern lv_obj_t * uic_Battery3Icon;
extern lv_obj_t * uic_Lux3Icon;
extern lv_obj_t * uic_Colorwheel3;
extern lv_obj_t * uic_Lux4Button;
extern lv_obj_t * uic_Lux4Label;
extern lv_obj_t * uic_Network4Icon;
extern lv_obj_t * uic_Battery4Icon;
extern lv_obj_t * uic_Lux4Icon;
extern lv_obj_t * uic_Colorwheel4;
extern lv_obj_t * uic_EasterButton;
extern lv_obj_t * uic_GemGlyph71Button;
extern lv_obj_t * uic_GemGlyph71Label;
extern lv_obj_t * uic_GemGlyph71Icon;
extern lv_obj_t * uic_GemGlyph71OutButton;
extern lv_obj_t * uic_GemGlyph71OutButtonLabel;
extern lv_obj_t * uic_EasterEggResult;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

