// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ArcaFace

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Container8;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label6;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Lantern11Button;
extern lv_obj_t * ui_Lantern11Label;
extern lv_obj_t * ui_Network11Icon;
extern lv_obj_t * ui_Battery11Icon;
extern lv_obj_t * ui_Lantern11Icon;
extern lv_obj_t * ui_Lantern12Button;
extern lv_obj_t * ui_Lantern12Label;
extern lv_obj_t * ui_Network12Icon;
extern lv_obj_t * ui_Battery12Icon;
extern lv_obj_t * ui_Lantern12Icon;
extern lv_obj_t * ui_Lantern13Button;
extern lv_obj_t * ui_Lantern13Label;
extern lv_obj_t * ui_Network13Icon;
extern lv_obj_t * ui_Battery13Icon;
extern lv_obj_t * ui_Lantern13Icon;
extern lv_obj_t * ui_Lantern14Button;
extern lv_obj_t * ui_Lantern14Label;
extern lv_obj_t * ui_Network14Icon;
extern lv_obj_t * ui_Battery14Icon;
extern lv_obj_t * ui_Lantern14Icon;
extern lv_obj_t * ui_Lantern15Button;
extern lv_obj_t * ui_Lantern15Label;
extern lv_obj_t * ui_Network15Icon;
extern lv_obj_t * ui_Battery15Icon;
extern lv_obj_t * ui_Lantern15Icon;
extern void ui_event_EasterButton(lv_event_t * e);
extern lv_obj_t * ui_EasterButton;
extern void ui_event_EggButton(lv_event_t * e);
extern lv_obj_t * ui_EggButton;
extern lv_obj_t * ui_EasterEggResult;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen2;
extern lv_obj_t * uic_Container2;
extern lv_obj_t * uic_Lantern11Button;
extern lv_obj_t * uic_Lantern11Label;
extern lv_obj_t * uic_Network11Icon;
extern lv_obj_t * uic_Battery11Icon;
extern lv_obj_t * uic_Lantern11Icon;
extern lv_obj_t * uic_Lantern12Button;
extern lv_obj_t * uic_Lantern12Label;
extern lv_obj_t * uic_Network12Icon;
extern lv_obj_t * uic_Battery12Icon;
extern lv_obj_t * uic_Lantern12Icon;
extern lv_obj_t * uic_Lantern13Button;
extern lv_obj_t * uic_Lantern13Label;
extern lv_obj_t * uic_Network13Icon;
extern lv_obj_t * uic_Battery13Icon;
extern lv_obj_t * uic_Lantern13Icon;
extern lv_obj_t * uic_Lantern14Button;
extern lv_obj_t * uic_Lantern14Label;
extern lv_obj_t * uic_Network14Icon;
extern lv_obj_t * uic_Battery14Icon;
extern lv_obj_t * uic_Lantern14Icon;
extern lv_obj_t * uic_Lantern15Button;
extern lv_obj_t * uic_Lantern15Label;
extern lv_obj_t * uic_Network15Icon;
extern lv_obj_t * uic_Battery15Icon;
extern lv_obj_t * uic_Lantern15Icon;
extern lv_obj_t * uic_EasterButton;
extern lv_obj_t * uic_EasterEggResult;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

